Restructuring the "Welcome" page for docs
spokestack/spokestack-website pull request #100
Opened 2020-09-15 21:48 UTC by miketatum

As we start using this page as our landing page for more of CTA's from the site and marketing, I wanted to make a bit more readable and inviting. The goal is to get people into tutorials and building ASAP.

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [X] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [ ] I have run `npm test` against my changes and tests pass.
- [ ] I have added or edited necessary documentation, or no docs changes are needed.

### Description

**Fixes**: #

2020-09-15 22:14 UTC, space-pope requested changes
Mostly looks fine—I think we have a missing link or two, and the quickstart guide links could fit into the copy a bit better. Originally those were the main CTA on this page and its primary raison d'être.

2020-09-15 22:14 UTC, space-pope commented on content/docs/welcome.md
> +1. **Custom Integration**: A custom integration gives the app developer full control of voice integration. For examples, check out the Spokestack Studio app on [iOS](https://apps.apple.com/us/app/spo
We don't have live Android sample apps, but we do have sample code on github.
```suggestion
1. **Custom Integration**: A custom integration gives the app developer full control of voice integration. For examples, check out the Spokestack Studio app on [iOS](https://apps.apple.com/us/app/spokestack-studio/id1508393980) or the control room sample app on [Android](https://github.com/spokestack/android-control-room).
```
I do need to update the Android sample app; I plan on doing that when the next version of the library is released (it's currently in PR review).

I wouldn't try to scare developers away from this path.

2020-09-15 22:14 UTC, space-pope commented on content/docs/welcome.md
> +As a tools and service provider, we try to balance ease of integration with customization for your voice interface needs.
```suggestion
As a tools and services provider, we try to balance ease of integration with customization for your voice interface needs.
```

2020-09-15 22:14 UTC, space-pope commented on content/docs/welcome.md
> +2. **Spokestack Tray**. Spokestack Tray is a library that provides a voice interface overlay on your mobile app. Spokestack Tray can still be customized to meet branding requirements, but follows a s
```suggestion
2. **Spokestack Tray**. Spokestack Tray is a library that provides a voice interface overlay on your mobile app. Spokestack Tray can still be customized to meet branding requirements, but follows a specific use pattern. See our demo "Bartender" app on [iOS](https://apps.apple.com/us/app/get-the-bartender/id1530425843) and [Android](https://play.google.com/store/apps/details?id=com.spokestack.bartender) for examples of how Tray works with existing apps—in this case, a generic recipe app. This is the path we recommend for _intermediate_ to _advanced_ mobile developers. Want to see how you might customize Spokestack Tray for your app? We have a [Figma template] that can help you visualize Tray in your app.
```

Looks like we need a link for that Figma template.

2020-09-15 22:14 UTC, space-pope commented on content/docs/welcome.md
> +Are you brand new to voice? Check out our [overview video](https://www.youtube.com/watch?v=wbJ8fZh-iQw) as well as the [_Concepts_]sections of our docs. We also have a [voice design guide](/docs/Desi
```suggestion
Are you brand new to voice? Check out our [overview video](https://www.youtube.com/watch?v=wbJ8fZh-iQw) and _Concepts_ section of our docs. We also have a [voice design guide](/docs/Design/getting-started) to help you get started. 
```

We'd need a landing page for `Concepts` to link to it.

2020-09-15 22:14 UTC, space-pope commented on content/docs/welcome.md
>  - [Java](/blog/porting-the-alexa-minecraft-skill-to-android-using-spokestack)
```suggestion
- [iOs](/blog/porting-a-smart-speaker-voice-app-to-mobile-part-1)
- [Android](/blog/porting-the-alexa-minecraft-skill-to-android-using-spokestack)
```
might as well have these match the previous section

2020-09-15 22:14 UTC, space-pope commented on content/docs/welcome.md
> +**Custom Integration? Start here...**
This should probably be merged with the `Custom Integration` section above instead of having that heading spread across two places like this.

2020-09-15 22:16 UTC, miketatum commented on content/docs/welcome.md
> +2. **Spokestack Tray**. Spokestack Tray is a library that provides a voice interface overlay on your mobile app. Spokestack Tray can still be customized to meet branding requirements, but follows a s
Weird, missing the Figma Template link: https://www.figma.com/file/LvU9UXNPElCcJ3XYrFXFif/Spokestack-Tray

2020-09-16 15:03 UTC, timmywil commented
I made some minor edits to the copy and organized the different subjects into their own sections. Let me know if this is good to go.

2020-09-16 15:03 UTC, timmywil approved these changes

2020-09-16 16:48 UTC, space-pope reviewed
Seems mostly good. Let me know if we want a `Concepts/index.md`.

2020-09-16 16:48 UTC, space-pope commented on content/docs/welcome.md
> +If you're new to voice, check out our [overview video](https://www.youtube.com/watch?v=wbJ8fZh-iQw) and [Concepts](/docs/Concepts/asr) section of our docs.
```suggestion
If you're new to voice, check out our [overview video](https://www.youtube.com/watch?v=wbJ8fZh-iQw) and the [Concepts](/docs/Concepts/asr) section of our docs.
```
I could whip up an `index.md` for this section fairly quickly if we want. ASR is the first piece of the puzzle, but going straight there from this welcome page seems like it'd be an abrupt experience.

2020-09-16 16:48 UTC, space-pope commented on content/docs/welcome.md
> +As a tools and services provider, we try to balance ease of integration with customization for your voice interface needs. Here are the ways you can integrate Spokestack into your mobile app:
```suggestion
As a tools and services provider, we try to balance ease of integration with customization for your voice interface needs. Here are the ways you can integrate Spokestack with your mobile app:
```

2020-09-16 16:48 UTC, space-pope commented on content/docs/welcome.md
> +1. **Spokestack Tray**: Spokestack Tray is a library that provides a voice interface overlay designed to work in any mobile app. Spokestack Tray is opinionated and follows a specific use pattern, but
```suggestion
1. **Spokestack Tray**: Spokestack Tray is a library that provides a voice interface overlay designed to work in any mobile app. Spokestack Tray is opinionated and follows a specific use pattern, but can be customized to meet your own branding requirements. This path is suitable for mobile developers of all experience levels, but it assumes some experience with the underlying platform (React Native, iOS, or Android). Check out our "Get the Bartender" app on [iOS](https://apps.apple.com/us/app/get-the-bartender/id1530425843) and [Android](https://play.google.com/store/apps/details?id=com.spokestack.bartender) for examples of how Tray might work with an existing app.
```

2020-09-16 16:48 UTC, space-pope commented on content/docs/welcome.md
> +1. **Custom Integration**: A custom integration gives the app developer full control over voice integration. This path is more suitable for _intermediate_ and _advanced_ mobile developers as it requi
```suggestion
1. **Custom Integration**: A custom integration gives the app developer full control over voice integration. This path is more suitable for _intermediate_ and _advanced_ mobile developers as it requires building familiarity with individual Spokestack subsystems. Check out the Spokestack Studio app on [iOS](https://apps.apple.com/us/app/spokestack-studio/id1508393980) or the control room sample app on [Android](https://github.com/spokestack/android-control-room) for examples of all of our services and how they work.
```

2020-09-16 16:50 UTC, miketatum commented on content/docs/welcome.md
> +If you're new to voice, check out our [overview video](https://www.youtube.com/watch?v=wbJ8fZh-iQw) and [Concepts](/docs/Concepts/asr) section of our docs.
That's a good idea. I obviously wasn't sure where to point to there.

2020-09-16 16:51 UTC, miketatum commented on content/docs/welcome.md
> +1. **Spokestack Tray**: Spokestack Tray is a library that provides a voice interface overlay designed to work in any mobile app. Spokestack Tray is opinionated and follows a specific use pattern, but
This was a great edit. Thank you.

2020-09-16 17:28 UTC, space-pope approved these changes
I obviously approve now :).

2020-09-16 19:00 UTC, merged

2020-09-16 20:43 UTC, timmywil commented
:tada: This PR is included in version 1.26.0 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack.io/releases/tag/1.26.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: