docs: fill out react native and ios docs topics
spokestack/spokestack-website pull request #104
Opened 2020-09-21 17:39 UTC by noelweichbrodt

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [X] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [X] I have run `npm test` against my changes and tests pass.
- [X] I have added or edited necessary documentation, or no docs changes are needed.

### Description

Add additional documentation topics on Speech Pipeline, NLU, and TTS for React Native and iOS

2020-09-21 17:49 UTC, timmywil requested changes
Some small changes

2020-09-21 17:49 UTC, timmywil commented on content/docs/React Native/speech-pipeline.md
> +![](images/speech_pipeline.png 'speech pipeline')
I think this sets a title, but alt text is more important. Set alt text in the square brackets `[]`.

2020-09-21 17:49 UTC, timmywil commented on content/docs/React Native/speech-pipeline.md
> +  ,"error":""
Place commas at the end of lines.

2020-09-21 17:49 UTC, timmywil commented on content/docs/React Native/speech-pipeline.md
> +}
Commas

2020-09-21 17:49 UTC, timmywil commented on content/docs/React Native/nlu.md
> +navId: NLU (React Native)
File needs to be added to `nav.json`

2020-09-21 19:27 UTC, space-pope reviewed
Just my normal PR savagery, including typos, link updates, and a couple questions.

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +Apple manages the various demands on an iOS devices audio system via [audio sessions](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduct
```suggestion
Apple manages the various demands on an iOS device's audio system via [audio sessions](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html). See their documentation for more details, but here's the minimum configuration you'll need in order to record user speech. A good place for it is your `AppDelegate`'s `application(_:didFinishLaunchingWithOptions)` method.
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +Then we configure a text-to-speech component using a TTS API key and secret that allow you to use Spokestack voices for free! You can also use your own api key & secret from [your Spokestack account
```suggestion
Then we configure a text-to-speech component using a TTS API key and secret that allow you to use Spokestack voices for free! You can also use your own api key & secret from [your Spokestack account page](/account/settings).
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +Finally we configure the natural language understanding component, which uses Spokestack NLU models. To test things out, just try one of our free NLU models on [your Spokestack account page](https://
```suggestion
Finally we configure the natural language understanding component, which uses Spokestack NLU models. To test things out, just try one of our free NLU models on [your Spokestack account page](/account/services/nlu), or grab this older [example NLU model](https://github.com/spokestack/spokestack-ios/blob/master/SpokestackFrameworkExample/nlu.tflite), [model metadata](https://github.com/spokestack/spokestack-ios/blob/master/SpokestackFrameworkExample/nlu.json), and [NLU vocabulary](https://d3dmqd7cy685il.cloudfront.net/nlu/vocab.txt).
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +// Spokestack configuration h as five top-level keys: 'input', 'stages', and 'properties' for the speech pipeline, 'tts' for text to speech, and 'nlu' for natural language recognition. Keys for asr,
```suggestion
// Spokestack configuration has five top-level keys: 'input', 'stages', and 'properties' for the speech pipeline, 'tts' for text to speech, and 'nlu' for natural language recognition. Keys for asr, tts, and nlu may be omitted if your app does not require them.
```

In the context of this paragraph, what is a 'key for asr'?

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +    'io.spokestack.spokestack.google.AndroidpeechRecognizer' // one of the three supported speech recognition services
```suggestion
    'io.spokestack.spokestack.android.AndroidSpeechRecognizer' // one of the four supported speech recognition services
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +    // 'io.spokestack.spokestack.android.GoogleSpeechRecognizer'
```suggestion
    // 'io.spokestack.spokestack.google.GoogleSpeechRecognizer'
    // 'io.spokestack.spokestack.asr.SpokestackCloudRecognizer'
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +    // 'google-credentials': YOUR_GOOGLE_VOICE_CREDENTIALS, // only set if using `GoogleSpeechRecognizer` stage above
I'm not a huge fan of leaving configuration we're not recommending in comments. As our supported features grow, this will get either unwieldy or unreliable. Instead of this and the other ASR providers above, I'd just point people to the ASR doc page, which could maybe use a bit of elaboration for RN.

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +You'll note that classification results are in a map containing an intent. A intent-based classifier will regularize all sorts of related langague into a single canonical intent, eg "let's go" or "pl
```suggestion
You'll note that classification results are in a map containing an intent. A intent-based classifier will regularize all sorts of related language into a single canonical intent, e.g. "let's go" and "please cease" get classified as `start` and `stop`, respectively. Slots may be thought of as parameters for your app to take action on, based on the intent. See our [NLU guide](/docs/Concepts/nlu) for more information on NLU in general and Spokestack's implementation. 
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/nlu.md
> +This is a companion to the [NLU concept guide](docs/Concepts/nlu), which discusses the NLU subsystem holistically. Here we'll talk about usage issues specific to the React Native client library.
```suggestion
This is a companion to the [NLU concept guide](/docs/Concepts/nlu), which discusses the NLU subsystem holistically. Here we'll talk about usage issues specific to the React Native client library.
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/nlu.md
> +    // NLU settings. Only set these if you are calling `Spokestack.classify`.
```suggestion
```
This guide is all about NLU, so assume these are required

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/nlu.md
> +The configuration properties above refer to the three required files for the Spokestack NLU model you're using.
Is it worth having a quick explainer here about how the filesystem paths work, maybe an example using rn-fetch's API? People seem to get tripped up here.

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/nlu.md
> +When it comes time to classify an utterance, Spokestack's NLU does all the heavy lifting in the background thread and returns the classification result via an event body.
```suggestion
When it comes time to classify an utterance, Spokestack's NLU does all the heavy lifting on a background thread and returns the classification result via an event body.
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/nlu.md
> +Then just call `classify` with the text you want to classify. The second argument, a dictionary, is currently unused.
```suggestion
Then just call `classify` with the text you want to classify. The second argument, a plain object, is currently unused.
```
The RN module could even hide it from its public API (or add a convenience method that omits it) until we have a service that uses it.

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/nlu.md
> +Your `onClassification` event will receive a dictionary with the following structure:
```suggestion
Your `onClassification` callback will receive an object with the following structure:
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/nlu.md
> +  ,"result": {
I get that this is technically valid/easier to update by hand, but do you ever actually _see_ JSON in the wild like this?

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/nlu.md
> +        "rawValue":"tea earl grey hot"
Looks like we lost the capitalization/punctuation from the original utterance here.

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/nlu.md
> +From there, your app takes over and acts on the intent and slots that have been classified!
```suggestion
From there, your app takes over and acts on the intent and slots!
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/speech-pipeline.md
> +If you've read any of our other documentation, you know that the speech pipeline is the main way you interact with Spokestack's speech recognition and wakeword. This guide is here to explain in a lit
```suggestion
If you've read any of our other documentation, you know that the speech pipeline is the main way you interact with Spokestack's speech recognition and wakeword. This guide is here to explain in a little more detail how the React Native version of Spokestack uses this architecture to recognize wakewords and user speech. Spokestack on React Native is just a wrapper around the [Android](/docs/Android/speech-pipeline) and [iOS](/docs/iOS/speech-pipeline) native libraries, so if you have more detailed platform-specific questions, be sure to consult those!
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/speech-pipeline.md
> +As the name implies, `SpeechPipeline` is a collection of distinct modular components that work together to process user speech. In short, the pipeline receives audio sends it through a variable numbe
```suggestion
As the name implies, `SpeechPipeline` is a collection of distinct modular components that work together to process user speech. In short, the pipeline receives audio from the microphone and sends it through a variable number of _stages_, each of which performs some form of processing and optionally dispatches events back through the pipeline.
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/speech-pipeline.md
> +Configuration available at build time include properties, described in [the configuration guide](/docs/Concepts/pipeline-configuration) and the various pipeline stages.
```suggestion
Configuration available at build time includes a list of pipeline stages and various properties, which are described in [the configuration guide](/docs/Concepts/pipeline-configuration).
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/speech-pipeline.md
> +While the pipeline is listening passively, it sends audio through its stages a frame at a time (a "frame" defaults to 20 ms of audio, but [it's configurable](/docs/Concepts/pipeline-configuration)).
```suggestion
While the pipeline is listening passively, it sends audio through its stages a frame at a time (a "frame" defaults to 20 ms of audio, but [it's configurable](/docs/Concepts/pipeline-configuration#runtime-tunable-parameters)). That audio is not leaving the device, though; it's waiting for a stage to recognize a trigger word or phrase and set the pipeline to active. The classes that do this in Spokestack typically have names that end in `Trigger`; see `WakewordTrigger` and `VoiceActivityTrigger` for examples.
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/speech-pipeline.md
> +The pipeline can also be activated by calling its `activate` method. This is what you'd do to implement push-to-talk. Once activated, it can be deactivated by calling `deactivate`, or it will remain
```suggestion
The pipeline can also be activated by calling its `activate` method. This is what you'd do to implement push-to-talk. Once activated, it can be deactivated by calling `deactivate`, or it will remain active until a pre-set timeout is triggered (see `wake-active-min` and `wake-active-max` in the [configuration documentation](/docs/Concepts/pipeline-configuration#runtime-tunable-parameters)).
```
These are the ones I just fixed in Android; until the next release this version won't work in Android (but won't cause an error), but afterwards it'll work in both.

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/speech-pipeline.md
> +When active, audio frames are not processed on-device but are instead sent to an ASR service to be transcribed (if an ASR component is registered in the pipeline; these components have names that end
Not technically true anymore (should probably be changed in the Android version too)—the recommended configuration for both platforms uses a presumably on-device ASR.

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/speech-pipeline.md
> +All events are optional, so apps can subscribe to whichever are of interest. All pipeline events send an event dictionary with a common set of keys. Here's an example of a `recognize` event:
```suggestion
All events are optional, so apps can subscribe to whichever are of interest. All pipeline events send an event object with a common set of keys. Here's an example of a `recognize` event:
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/tts.md
> +    'spokestack-id': 'f0bc990c-e9db-4a0c-a2b1-6a6395a3d97e', // your Spokestack API ID
Worth considering reading these from `properties` instead since they're applicable to 2/3 of the pipeline stages, and possibly to NLU as well if we release a cloud version.

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/tts.md
> +Generating a URL to a audio stream of a tts synthesized voice is just a single method in Spokestack!
```suggestion
Generating a URL to an audio stream of a TTS synthesized voice is just a single method in Spokestack!
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/tts.md
> +We'll break down what was included in the `synthesize` arguments here, and there's also more details on the [API documentation](https://github.com/spokestack/react-native-spokestack#methods):
```suggestion
We'll break down what was included in the `synthesize` arguments here; there's even more detail in the [API documentation](https://github.com/spokestack/react-native-spokestack#methods):
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/React Native/tts.md
> +The `voice` argument allows you to specify which of Spokestack's library of synthetic voices you wish to use. Want something besides `demo-male`? [Create a Spokestack account](/create) to get your ow
```suggestion
The `voice` argument allows you to specify which of Spokestack's library of synthetic voices you wish to use. Want something besides `demo-male`? [Create a Spokestack account](/create) to get your own free access to additional voices!
```
Which free additional voices?

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +We also use the default credentials for `SpeechConfiguration.apiId` and `SpeechConfiguration.apiSecret` are set to public values that let you try Spokestack TTS without creating an account. [Create a
```suggestion
We also use the default credentials for `SpeechConfiguration.apiId` and `SpeechConfiguration.apiSecret`, which are set to public values that let you try Spokestack TTS without creating an account. [Create an account](/create) or [sign in](/login) to get your own free API credentials and access to additional features!
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +Generating a URL to a audio stream of a tts synthesized voice is just a single method in Spokestack!
```suggestion
Generating a URL to an audio stream of a TTS synthesized voice is just a single method in Spokestack!
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +`TextToSpeechInput` has additional properties that you can use for more sophisticated speech synthesis that we will detail briefly. As always, there's more details on the [API documentation](https://
```suggestion
`TextToSpeechInput` has additional properties that you can use for more sophisticated speech synthesis that we will detail briefly. As always, there's more detail in the [API documentation](https://spokestack.github.io/spokestack-ios/Classes/TextToSpeechInput.html)
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +This is the simplest arity of `synthesize`, which just takes a plain text string as input. The `success(TextToSpeechResult:)` delegate function will be called with the result, which has a `url` prope
Technically it takes an instance of `TextToSpeechInput`—it might be worth adding a convenience method that takes a string.

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +The `input` is simply the string you want to hear synthesized.
Might want to include a line like "Its full constructor looks like this:" somewhere above here; without a reference, the rundown of the fields seems a little abrupt to me.

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +The `voice` argument allows you to specify which of Spokestack's library of synthetic voices you wish to use. Want something besides `demo-male`? [Create a Spokestack account](/create) to get your ow
Again, not sure we should have that last phrase.

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +The `id` property optionally allows you to track individual tts synthesis requests, and it will be echoed back in the corresponding [`TextToSpeechResult.id`](https://spokestack.github.io/spokestack-i
```suggestion
The optional `id` property allows you to track individual TTS synthesis requests; it will be echoed back in the corresponding [`TextToSpeechResult.id`](https://spokestack.github.io/spokestack-ios/Classes/TextToSpeechResult.html).
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +To save it for later, a simple download before the 60 second TTL expires can be done:
```suggestion
To save it for later, you can simply download the audio before the 60-second TTL expires:
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +Use your own `AVPlayer` instance to control playback:
```suggestion
To use your own `AVPlayer` instance to control playback:
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +Want to skip all that and let Spokestack handle the both the synthesis and playback of your synthesis? We've combined all the above two sections into a single function call! Try `speak(TextToSpeechIn
```suggestion
Want to skip all that and let Spokestack handle the both the synthesis and playback of your synthesis? We've combined the two sections above into a single function call! Try `speak(TextToSpeechInput:)`!
```

2020-09-21 19:27 UTC, space-pope commented on content/docs/iOS/tts.md
> +You'll receive event notifications when the synthesis been completed (`success`), begun playback (`didBeginSpeaking`) and finished playback (`didFinishSpeaking`). A whole TTS feature in just one func
```suggestion
You'll receive event notifications when synthesis has completed (`success`), playback has begun (`didBeginSpeaking`) and playback has finished (`didFinishSpeaking`). A whole TTS feature in just one function call!
```

2020-09-21 20:51 UTC, noelweichbrodt commented on content/docs/React Native/getting-started.md
> +    // 'google-credentials': YOUR_GOOGLE_VOICE_CREDENTIALS, // only set if using `GoogleSpeechRecognizer` stage above
agreed

2020-09-21 21:19 UTC, noelweichbrodt commented on content/docs/React Native/tts.md
> +    'spokestack-id': 'f0bc990c-e9db-4a0c-a2b1-6a6395a3d97e', // your Spokestack API ID
yes, that will be outside the scope of this doc though

2020-09-21 21:21 UTC, space-pope commented on content/docs/React Native/tts.md
> +    'spokestack-id': 'f0bc990c-e9db-4a0c-a2b1-6a6395a3d97e', // your Spokestack API ID
Totally. I just note these things as I see them so I don't forget to note them.

2020-09-21 21:37 UTC, noelweichbrodt commented on content/docs/React Native/nlu.md
> +The configuration properties above refer to the three required files for the Spokestack NLU model you're using.
oh yeah i actually meant to do this, thanks

2020-09-21 22:01 UTC, space-pope commented on content/docs/React Native/speech-pipeline.md
> +When active, audio frames are sent through an ASR service (selectably on-device or cloud-based) to be transcribed (if an ASR component is registered in the pipeline; these components have names that
```suggestion
When active, audio frames are sent through an ASR service (on-device or cloud-based) to be transcribed (if an ASR component is registered in the pipeline; these components have names that end in `SpeechRecognizer`). These ASR requests end when a pre-set timeout is reached or when the pipeline is manually set to inactive. At that point, the ASR service's best effort at a transcription is delivered via a speech event to any registered listeners.
```

2020-09-21 22:02 UTC, space-pope commented on content/docs/iOS/tts.md
> +This is the simplest arity of `synthesize`, which takes a constructor of `TextToSpeechInput` with a plain text string as input. The `success(TextToSpeechResult:)` delegate function will be called wit
```suggestion
This is the simplest arity of `synthesize`, which takes an instance of `TextToSpeechInput` constructed with a plain text string as input. The `success(TextToSpeechResult:)` delegate function will be called with the result, which has a `url` property with the audio stream.
```

2020-09-22 02:47 UTC, noelweichbrodt commented
@timmywil looks like there's a build failure when building the thumbnails?

2020-09-22 14:05 UTC, timmywil commented
@noelweichbrodt That's been fixed in develop. You can fix by rebasing.

2020-09-22 14:16 UTC, timmywil approved these changes

2020-09-22 14:17 UTC, merged