Update RN docs with simplified config
spokestack/spokestack-website pull request #126
Opened 2020-11-06 19:21 UTC by noelweichbrodt

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [X] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [X] I have run `npm test` against my changes and tests pass.
- [X] I have added or edited necessary documentation, or no docs changes are needed.

### Description

2020-11-06 21:00 UTC, space-pope reviewed
LGTM; just a typo and a suggestion.

2020-11-06 21:00 UTC, space-pope commented on content/docs/React Native/cookbook.md
> +To use the demo "Spokestack" wakeword, you'll need the demo TensorFlow Lite models: [detect](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/detect.tflite) | [encode](https://d3dmqd7cy685
```suggestion
To use the demo "Spokestack" wakeword, you'll need the demo TensorFlow Lite models: [detect](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/detect.tflite) | [encode](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/encode.tflite) | [filter](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/filter.tflite). The pipeline defaults to a wakeword-activated profile (`TFLITE_WAKEWORD_NATIVE_ASR`), so we don't need to specify it.
```

2020-11-06 21:00 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +Android SDK 24+, Android NDK (available from the `SDK Manager` -> `SDK Tools` tab in Android Studio or at [developer.android.com/ndk/downloads](https://developer.android.com/ndk/downloads)).
The NDK actually shouldn't be required unless you're doing development on the native library. This was something I erroneously had in the Android quickstart for awhile, but recently removed. Still wondering whether API 24 is a hard minimum.

2020-11-06 21:00 UTC, space-pope commented on content/docs/React Native/getting-started.md
> +// Spokestack configuration has four top-level keys: 'properties' for general Spokestack usage, 'pipeline' for the speech pipeline, 'tts' for text to speech, and 'nlu' for natural language recognitio
```suggestion
// Spokestack configuration has four top-level keys: 'properties' for general Spokestack usage, 'pipeline' for the speech pipeline, 'tts' for text to speech, and 'nlu' for natural language understanding. Keys for asr, tts, and nlu may be omitted if your app does not require them.
```

2020-11-06 21:00 UTC, space-pope commented on content/docs/React Native/tts.md
> +  // omitting pipeline and nlu configuration
```suggestion
  // omitting pipeline and nlu configuration; using tts defaults
```
Just a suggestion. It might feel to some readers like leaving out all the keys means they're not using any of them.

2020-11-06 22:09 UTC, timmywil requested changes
Some copy suggestions. Also, I think we should mention the version of RNS at which profiles are available.

2020-11-06 22:09 UTC, timmywil commented on content/docs/React Native/cookbook.md
> +When configuring Spokestack, just use a Push to Talk profile, prefixed with `PTT`:
```suggestion
When configuring Spokestack, use a Push to Talk profile, prefixed with `PTT`:
```

2020-11-06 22:09 UTC, timmywil commented on content/docs/React Native/cookbook.md
> +  pipeline: {
```suggestion
Spokestack.initialize({
  pipeline: {
```

2020-11-06 22:09 UTC, timmywil commented on content/docs/React Native/cookbook.md
> +    'profile': Spokestack.PipelineProfile.PTT_NATIVE_ASR
```suggestion
    profile: Spokestack.PipelineProfile.PTT_NATIVE_ASR
```

2020-11-06 22:09 UTC, timmywil commented on content/docs/React Native/cookbook.md
> +  }
```suggestion
  }
})
```

2020-11-06 22:09 UTC, timmywil commented on content/docs/React Native/cookbook.md
>  Then it's just a matter of calling `activate()` when a button is pushed!
```suggestion
Once Spokestack is initialized, call `activate()` to start listening.
```

2020-11-06 22:58 UTC, space-pope approved these changes

2020-11-09 17:50 UTC, noelweichbrodt commented
@timmywil satisfied with my changes, or do I need to update anything?

2020-11-09 18:23 UTC, timmywil commented on content/docs/React Native/cookbook.md
> +Beginning in version 4.0.0, using tap to talk is incredibly simple!
```suggestion
Beginning in version 4.0.0, the configuration for tap-to-talk has been greatly simplified.
```

What about a compromise? :P

2020-11-09 19:04 UTC, merged