Added Python Documentation
spokestack/spokestack-website pull request #128
Opened 2020-11-20 17:42 UTC by will-rice

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [x] I have run `npm test` against my changes and tests pass.
- [x] I have added or edited necessary documentation, or no docs changes are needed.

### Description

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/getting-started.md
> +        WakewordTrigger("path_to_tflite_model"),
does the `WakewordTrigger()` take a path to a folder containing the three wakeword models? If so, maybe say 
```suggestion
        WakewordTrigger("path_to_tflite_model_folder"),
```

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/getting-started.md
> +nlu = TFLiteNLU("path_to_tflite_model")
same question as above. is this a folder containing the nlu model + vocab + metadata? if so 
```suggestion
nlu = TFLiteNLU("path_to_tflite_model_folder")
```

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/getting-started.md
> +    tts.synthesize("welcome to spokestack")
Forgive my ignorance here, will `synthesize` perform automatic playback? If so, is there a way to just get the synthesis file itself?

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/tts.md
> +Text-to-speech is a broad topic, but as far as Spokestack is concerned, there are two things your app has to handle: sending text or SSML to be synthesized, and playing the resulting audio for your u
Does the python tts client support SpeechMarkup?

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/tts.md
> +manager.synthesize(utterance="welcome to spokestack", mode="text", voice="demo-male")
It would be good to show an example using SSML as well.

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/tts.md
> +Similar to the other callbacks, TTS will need to be registered as a response to an event when used in the `SpeechPipeline`. Below, is a sample that speaks back what the ASR component recognized.
Does the TTS component have a callback for the synthesis result?

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/nlu.md
> +The path to the directory containing these files is passed as the `model_dir` argument on initialization of the NLU.
ah, you may want to revise `getting-started.md` to include this information (it can be as minimal as an inline comment in the example code)

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/nlu.md
> +As mentioned in the [Getting Started](getting-started) guide, initializing the Spokestack NLU is done using a fluent interface, just like other Spokestack components.
afaik `fluent interface` is a technical term for the Builder pattern, which is not what this example is showing.

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/nlu.md
> +NLU results are returned in a wrapper that allows for easy access of the properties. The `Result` class contains:
it would be good to include a code snippet where you give an example output of the `Result` class.

2020-11-20 20:44 UTC, noelweichbrodt commented on content/docs/Python/speech-pipeline.md
> +### Use a Profile (Optional)
I would use the Profile interface as your default example, and move the stage interface to this optional section instead. Or even just move it to a Cookbook or something, imo nobody wants to deal with stages when profiles are available instead.

2020-11-20 20:50 UTC, will-rice commented on content/docs/Python/getting-started.md
> +        WakewordTrigger("path_to_tflite_model"),
I'll do what I did for NLU here.

2020-11-20 20:51 UTC, will-rice commented on content/docs/Python/getting-started.md
> +nlu = TFLiteNLU("path_to_tflite_model")
It's in the NLU part, but I'll make it both places so you don't need both of them.

2020-11-20 20:53 UTC, will-rice commented on content/docs/Python/getting-started.md
> +    tts.synthesize("welcome to spokestack")
Synthesize from the TTSManger class does automatic playback. We did add the url option though so I missed that.

2020-11-20 20:55 UTC, will-rice commented on content/docs/Python/speech-pipeline.md
> +### Use a Profile (Optional)
Thanks for pointing this out. I will carry this over to the tutorials.

2020-11-20 20:56 UTC, space-pope requested changes
I took this opportunity to do a little more fine-grained editing to the quickstart guide. See what you think.

Some of my comments will overlap with Noel's; sorry about that. He beat me to the punch, submitting while I was still reading.

The main reason for the red x is that we need to rework the mention of fluent interfaces and the "callbacks" sections of a couple of the modules that don't have them.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +There are some system dependencies that need to be downloaded in order to install spokestack via pip.
```suggestion
There are some system dependencies that need to be downloaded in order to install Spokestack via pip.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +We currently do not support Windows 10 natively, and recommend you install [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install-win10) with the Debian dependencies
```suggestion
We currently do not support Windows 10 natively, and recommend you install [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install-win10) with the Debian dependencies. However, if you would like to work on native Windows support, we gladly accept pull requests.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +Another potential avenue for using `spokestack` on Windows 10 is from [anaconda](https://www.anaconda.com/). This is without support for Text To Speech (TTS) though due to the Lame dependency. PortAu
```suggestion
Another potential avenue for using Spokestack on Windows 10 is via [anaconda](https://www.anaconda.com/). PortAudio can be installed via `conda`, but Lame cannot. Hence, microphone input will be supported, but text-to-speech will not.
```

I reordered these because it feels odd to read two sentences in a row that introduce an exception to the previous sentence.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +We use `pyenv` for virtual environments. Below you will find the step-by-step commands to install a virtual environment.
```suggestion
We use `pyenv` for virtual environments.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +The full Tensorflow package is installed with the following:
```suggestion
This library requires a way to run [TFLite](https://www.tensorflow.org/lite) models. There are two ways to add this ability. The first is installing the full [Tensorflow](https://www.tensorflow.org/) library:
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +
```suggestion
```

The last section says "The first [way]", but it never discusses the second—this is easier to recognize as the second installation method if it's not separated by a header line.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +In order for your application to use the Spokestack features, there are a few things you will need:
```suggestion
In order for your application to use Spokestack's features, there are a few things you will need:
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +Go to [spokestack.io](/account/) to set up your own account (it's free!). Once you've got that, go [grab one of our free NLU models](/account/services/nlu). We'll use the `Highlow` one in this exampl
```suggestion
Go to [spokestack.io](/create) to set up your own account (it's free!). Once you've got that, go [grab one of our free NLU models](/account/services/nlu). We'll use the `Highlow` one in this example, but you can choose another, or [create your own](/docs/concepts/nlu-training-data)
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +- Audio Output Device
```suggestion
- A free Spokestack account
- Audio input device
- A `SpeechPipeline` instance
- Audio output device
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +- Audio Output Device
These should be consistent—either the things I've lowercased should be lowercased, or "instance" should be capitalized (and I'd recommend following the same for the section headers below). I prefer to not overuse capitalization, so I went this way; the other way's probably OK too.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +Once you've downloaded your NLU, unzip `nlu.tar.gz` and add the directory with the three files inside (`metadata.json`, `nlu.tflite`, `vocab.txt`) to your Python project.
I might add a sentence about how it doesn't matter where they're added since you'll be passing paths to them later on—technically, they don't even need to be "in the project".

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +If the event is `recognize`, the raw text of what the user said can be found in `context.transcript`. Translating the text into an action is the job of the [Natural Language Understanding (NLU)](/doc
```suggestion
If the event is `recognize`, the raw text of what the user said can be found in `context.transcript`. Translating the text into an action is the job of the [Natural Language Understanding (NLU)](/docs/concepts/nlu) component. A great thing about Spokestack NLU models is that they run entirely on device. The NLU can be initialized like this:
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +If the event is `recognize`, the raw text of what the user said can be found in `context.transcript`. Translating the text into an action is the job of the [Natural Language Understanding (NLU)](/doc
We haven't talked about events yet, so it's abrupt to say "the event"—what event, and from where?

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +- [high-level NLU guide](/docs/Concepts/nlu)
```suggestion
- [high-level NLU guide](/docs/concepts/nlu)
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +- [converting an Alexa or Dialogflow NLU model](/docs/Concepts/export)
```suggestion
- [converting an Alexa or Dialogflow NLU model](/docs/concepts/export)
- [creating an NLU model from scratch](/docs/concepts/nlu-training-data)
```
I see where you got this list from...I'll make a mental note that the Android guide could use this same addition.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/getting-started.md
> +If you want the full smart speaker experience, you will need to give your application a voice. This can be achieved with text-to-speech (TTS). For more information on TTS, see the [TTS concept guide]
```suggestion
If you want the full smart speaker experience, you will need to give your application a voice. This can be achieved with text-to-speech (TTS). For more information on TTS, see the [TTS concept guide](/docs/concepts/tts). TTS playback uses `PyAudioOutput` class, which plays audio with the default speaker for the device. Like NLU, TTS can be used in a callback. Take a look at the example below, which simply speaks what the ASR heard.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/nlu.md
> +This is a companion to the [NLU concept guide](/docs/Concepts/nlu), which is a detailed outline of the NLU module. Here we'll talk about usage issues specific to the Python client library.
```suggestion
This is a companion to the [NLU concept guide](/docs/concepts/nlu), which is a detailed outline of the NLU module. Here we'll talk about usage issues specific to the Python client library.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/nlu.md
> +As a brief recap to the [guide](/docs/Concepts/nlu), every NLU model will have the three files.
```suggestion
As mentioned in the concept guide, every NLU model will have three files:
```

I wouldn't say this one point is a summary of the whole other guide.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/nlu.md
> +As mentioned in the [Getting Started](getting-started) guide, initializing the Spokestack NLU is done using a fluent interface, just like other Spokestack components.
This isn't true for Python. "Fluent interface" refers to the builders used in Android that let you set individual components via call chaining. The Python library doesn't have builders; you pass everything you need directly into the class constructor.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/nlu.md
> +- `slots` slots tagged by the model
```suggestion
- `utterance`: unmodified transcript received by the NLU
- `intent`: classified user intent
- `confidence`: model confidence in intent classification
- `slots`: slots tagged by the model
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/nlu.md
> +The callback for the NLU is going to take place on the "recognize" event. Take a look at the pipeline [guide](speech-pipeline) for a detailed explanation of callbacks. Below, is a sample of an NLU ca
What you're describing isn't a callback for NLU; it's a speech pipeline event. In Android, NLU processing is done on a background thread to avoid blocking the UI, so the result is returned by a callback. NLU is synchronous in Python, so this section should be reworded or removed.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +The `SpeechPipeline` offers the ability to execute code based on events that occur within the pipeline. These callbacks are initialized with the `@pipeline.event` [decorator](https://www.python.org/d
```suggestion
The `SpeechPipeline` offers the ability to execute code based on events that occur within the pipeline. These callbacks are registered with the `@pipeline.event` [decorator](https://www.python.org/dev/peps/pep-0318/). All callbacks should follow the naming convention of `on_{event}`. A basic callback that prints the ASR transcript to console is given below.
```

I'd either document the alternative of passing `name` to the decorator or remove support for it in the code.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +The `SpeechPipeline` offers the ability to execute code based on events that occur within the pipeline. These callbacks are initialized with the `@pipeline.event` [decorator](https://www.python.org/d
Also, there needs to be a list of available events somewhere. In Android, the events are in an enum, so they're available via the [API reference](https://www.javadoc.io/doc/io.spokestack/spokestack-android/latest/io/spokestack/spokestack/SpeechContext.Event.html), but unless I've missed it, these aren't documented in the Python library itself.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +Profiles are preset configurations for the `SpeechPipeline` that bundle input and stage classes into an easy-to-use wrapper. All profiles are designed to be initialized with only one line.
I actually missed the addition of this feature. Nice.

Just like the pipeline events, there should ideally be a list of pipeline profiles and brief descriptions somewhere. Maybe readthedocs covers this.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +There are a few other methods available to the `SpeechPipeline` which control the flow of information through the pipeline. All of these methods are accessible through callbacks. However, `pause` and
```suggestion
There are a few other methods available to the `SpeechPipeline` which control the flow of information through the pipeline. All of these methods are accessible through callbacks. However, `pause` and `resume` are designed to be used to temporarily stop the flow of audio while other computation is being performed, and can be called multiple times throughout the life of the pipeline.
```

I'm a little confused by the "methods are accessible through callbacks" wording. What's the intended use of a pipeline method in a callback?

You might add " (e.g., to stop the pipeline from processing audio while TTS audio is playing)" after "other computation is being performed", though you might also consider adding events that signal the start/stop of automatic playback to make this usage a little easier.

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +The stop method is a permanent stop of the pipeline and should be called when closing the application using the pipeline.
```suggestion
The `stop` method is a permanent stop of the pipeline and should be called when closing the application using the pipeline.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +The start methods initializes the pipeline and must always be called first before audio can be read into the pipeline.
```suggestion
The `start` method initializes the pipeline and must always be called first before audio can be read from the input device.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +The pause method is a temporary stop of the pipeline flow.
```suggestion
The `pause` method is a temporary stop of the pipeline flow.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +The resume method should be called after every pause to restart the audio flow.
```suggestion
If the pipeline is paused, `resume` must be called to restart the audio flow.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/tts.md
> +Text-to-speech is a broad topic, but as far as Spokestack is concerned, there are two things your app has to handle: sending text or SSML to be synthesized, and playing the resulting audio for your u
```suggestion
Text-to-speech is a broad topic, but as far as Spokestack is concerned, there are two things your app has to handle: sending text, SSML, or Speech Markdown to be synthesized; and playing the resulting audio for your users. This guide will cover both.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/tts.md
> +The best way to synthesize speech in Spokestack is to use the TextToSpeechManager module. Keep in mind that these modules operate independently of the `SpeechPipeline`.
```suggestion
The best way to synthesize speech in Spokestack is to use the `TextToSpeechManager` module. Keep in mind that this module operates independently of the `SpeechPipeline`.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/tts.md
> +The `TextToSpeechManager` is initialized as follows:
```suggestion
`TextToSpeechManager` is initialized as follows:
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/tts.md
> +If you haven't already, you will need to [create an account](/create) or [sign in](/login) to get your API credentials. See the [TTS concept guide](/docs/Concepts/tts) for additional information abou
```suggestion
If you haven't already, you will need to [create an account](/create) or [sign in](/login) to get your API credentials. See the [TTS concept guide](/docs/concepts/tts) for additional information about the types that are supported for the `mode` argument.
```

2020-11-20 20:56 UTC, space-pope commented on content/docs/Python/tts.md
> +### Callbacks
Again, this section would be appropriate if you had callbacks specific to TTS—things like [`TTSEvent.Type`](https://www.javadoc.io/doc/io.spokestack/spokestack-android/latest/io/spokestack/spokestack/tts/TTSEvent.Type.html) in Android.

Crucially, you _don't_ usually want to hook TTS up to the pipeline like this example does, as it's skipping the NLU piece, preventing the app from doing anything with the transcript before responding.

2020-11-23 18:55 UTC, will-rice commented on content/docs/Python/tts.md
> +Similar to the other callbacks, TTS will need to be registered as a response to an event when used in the `SpeechPipeline`. Below, is a sample that speaks back what the ASR component recognized.
No. It's only accessible via a pipeline event handler.

2020-11-23 20:52 UTC, will-rice commented
This is still in progress. I'm working on better documentation for the pipeline profiles. I'll request review when finished and you can look again.

2020-11-24 22:49 UTC, noelweichbrodt commented on content/docs/Python/tts.md
> +
Include an example using SSML + the URL option please

2020-11-25 00:27 UTC, will-rice commented on content/docs/Python/tts.md
> +
I added Speech Markdown as well. The URL option is only available when using `TextToSpeechClient` alone, but I'm not sure if someone would want automatic playback and URL at the same time. If that's useful, I can update `TextToSpeechManager` to include a synthesize to URL option also.

2020-11-25 02:09 UTC, noelweichbrodt commented on content/docs/Python/tts.md
> +
Ah, ok, so then just provide an example of using `TextToSpeechClient` alone, since you're right, it probably won't be a use case to get both the URL and the playback. Or update `TextToSpeechManager` as you suggest, whichever you think is the best way to accommodate a URL-only use case.

2020-11-25 15:50 UTC, will-rice commented on content/docs/Python/tts.md
> +
The example is at the bottom of tts.md

2020-11-30 17:28 UTC, space-pope reviewed
Good stuff; just have a few suggestions below.

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/getting-started.md
> +We use `pyenv` for virtual environments.
```suggestion
We use [`pyenv`](https://github.com/pyenv/pyenv) for virtual environments.
```

Might as well...I should've suggested this earlier.

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/getting-started.md
> +The `SpeechPipeline` [guide](speech-pipeline) has a detailed explanation of how to set up the pipeline, so we will show the quickest way here using a profile.
We haven't explained what the pipeline or profiles are at this point, so maybe a quick introduction for each...

```suggestion
Spokestack's speech pipeline handles collecting audio from the input device and transcribing speech directed at your app. The [`SpeechPipeline` guide](speech-pipeline) has a detailed explanation of how to set up the pipeline, so we will show the quickest way here using a profile, which configures the pipeline's components for a specific use case. The profile we use here includes wakeword activation and speech transcription using Spokestack's cloud ASR.
```

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/getting-started.md
> +Input to the NLU model is the ASR transcript. The transcript can be accessed as a property of `SpeechContext`. Below is a sample Event Handler for running inference on the speech transcript.
```suggestion
Input to the NLU model is the ASR transcript. The transcript can be accessed as a property of `SpeechContext`. Below is a sample event handler for running inference on the speech transcript.
```

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/getting-started.md
> +If you want the full smart speaker experience, you will need to give your application a voice. This can be achieved with text-to-speech (TTS). For more information on TTS, see the [TTS concept guide]
```suggestion
If you want the full smart speaker experience, you will need to give your application a voice. This can be achieved with text-to-speech (TTS). For more information on TTS, see the [TTS concept guide](/docs/concepts/tts). TTS playback uses the `PyAudioOutput` class, which plays audio with the default speaker for the device. Like NLU, TTS can be used in an event handler. Take a look at the example below, which simply speaks what the ASR heard.
```

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/nlu.md
> +print(f"slots: {result.slots}")
This is a bit of an awkward way to give an example of an object. I'm not sure you need to spell things out at this level; you could just leave it at "Each of these properties is stored in a field on the `Result` object in the previous section.

If you want to show it printed to the console, though, it'd be better to just implement `__repr__` and have an example that looks more like:

```shell
>> result
Result(utterance: turn the lights on in the kitchen, ...)
```

While you're at it, you probably don't want to just print the keys for `slots`; you'd want a full representation of the dict.

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +The `SpeechPipeline` offers the ability to execute code based on events that occur within the pipeline. These handlers are registered with the `@pipeline.event` [decorator](https://www.python.org/dev
```suggestion
The `SpeechPipeline` offers the ability to execute code based on events that occur within the pipeline. These handlers are registered with the `@pipeline.event` [decorator](https://www.python.org/dev/peps/pep-0318/). Handlers can follow the naming convention of `on_{event}` or pass the `name` argument to the decorator, using the name of a pipeline event as its value. A basic handler that prints the ASR transcript to console, for both conventions, is given below.
```

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +@pipeline.event(name="get_transcript")
Wouldn't this be
```suggestion
@pipeline.event(name="recognize")
```

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +- `activate`: occurs when `SpeechContext` is activated.
"Activated" is a bit of inside baseball. We need to tell people what this means.
```suggestion
- `activate`: occurs when the pipeline's `SpeechContext` is activated (when ASR transcription begins).
```

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +- `deactivate`: occurs when `SpeechContext` is deactivated.
```suggestion
- `deactivate`: occurs when the pipeline's `SpeechContext` is deactivated (when transcription stops).
```

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +- `step`: occurs when a single frame is processed by the pipeline.
(Comment on the code, not the docs)

This is a pretty chatty event...and it fires even when the pipeline's paused. I'm skeptical of its overall usefulness. The other libraries have `timeout` and `error` events that would be good to have in Python.

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +The `start` methods initializes the pipeline and must always be called first before audio can be read into the pipeline.
```suggestion
The `start` method initializes the pipeline and must be called before audio can be read into the pipeline.
```

2020-11-30 17:28 UTC, space-pope commented on content/docs/Python/tts.md
> +If automatic playback is **not** what you are looking for we offer another option. An instance of
```suggestion
If automatic playback is **not** what you are looking for, we offer another option. An instance of
```

2020-11-30 18:46 UTC, will-rice commented on content/docs/Python/nlu.md
> +print(f"slots: {result.slots}")
> it would be good to include a code snippet where you give an example output of the `Result` class.
 this is based on what Noel said. `__repr__` is definitely the right way to handle output though. So I can add `__repr__` to `Result`

2020-11-30 18:48 UTC, will-rice commented on content/docs/Python/speech-pipeline.md
> +@pipeline.event(name="get_transcript")
I will check on this, but iirc the `name` argument is the name of the function not the name of the event. so in the `def on_recognize` case, `name` is the function name passed to the decorator.

2020-11-30 18:53 UTC, will-rice commented on content/docs/Python/speech-pipeline.md
> +There are a few other methods available to the `SpeechPipeline` which control the flow of information through the pipeline. All of these methods are accessible through callbacks. However, `pause` and
that should have been changed to "event handler"

2020-11-30 18:56 UTC, will-rice commented on content/docs/Python/nlu.md
> +print(f"slots: {result.slots}")
Is there a better way of showing example output without printing to console?

2020-11-30 18:58 UTC, space-pope commented on content/docs/Python/nlu.md
> +print(f"slots: {result.slots}")
Since it's just a data object, not really—I missed the original comment there and am not sure I really agree with it. Doesn't hurt anything to include it, though, and having a `__repr__` for this class would be good anyway.

2020-11-30 19:02 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +@pipeline.event(name="get_transcript")
[The method doc](https://github.com/spokestack/spokestack-python/blob/master/spokestack/context.py#L36) mentions the name of the handler, but all the call sites for that method pass event names, meaning that `self.handlers` would have to have keys that match the events.

2020-11-30 19:07 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +@pipeline.event(name="get_transcript")
If the name of the function were required, you wouldn't need to pass it to the decorator; you should be able to access that name inside the decorator itself.

2020-11-30 20:08 UTC, will-rice commented on content/docs/Python/speech-pipeline.md
> +@pipeline.event(name="get_transcript")
> [The method doc](https://github.com/spokestack/spokestack-python/blob/master/spokestack/context.py#L36) mentions the name of the handler, but all the call sites for that method pass event names, meaning that `self.handlers` would have to have keys that match the events.

this is the event in SpeechContext and not what we are using to decorate the event handlers.
https://github.com/spokestack/spokestack-python/blob/55e61ba23699d5ed376427ce86ae5dc735f6805b/spokestack/pipeline.py#L85

2020-11-30 20:20 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +@pipeline.event(name="get_transcript")
Right, but the decorator you linked calls `add_handler` in `SpeechContext`, storing either the value of `name` or the fn name minus "on_" in the handler map. That map is then queried when an actual event happens—the name of that event has to be a key in `self.handlers` in order for the function associated with it to be called.

This actually brings up another potential problem with the design, depending on the use case: You can only register one function for a given pipeline event. `add_handler` has the semantics of `set_handler`.

2020-11-30 20:27 UTC, will-rice commented on content/docs/Python/speech-pipeline.md
> +@pipeline.event(name="get_transcript")
I think this PR should focus on what is currently there and not what should be there. Then if you have problems with the python library, we can fix those, then update the docs.

2020-11-30 20:30 UTC, space-pope commented on content/docs/Python/speech-pipeline.md
> +@pipeline.event(name="get_transcript")
Totally; the second paragraph was just to spur thought about the library. The rest is still relevant, as we want to make sure we're describing the right thing.

2020-11-30 20:36 UTC, will-rice commented on content/docs/Python/speech-pipeline.md
> +- `step`: occurs when a single frame is processed by the pipeline.
`timeout` is actually there, but I missed adding it to the list.

2020-12-01 16:39 UTC, space-pope approved these changes
Sorry; I missed the resolution of the event decorator bit yesterday. LGTM; thanks for all the updates!

2020-12-03 05:52 UTC, merged