docs: move inappropriate content out of /docs/Concepts and into new sections; expand /docs/Concepts
spokestack/spokestack-website pull request #159
Opened 2021-03-18 19:41 UTC by noelweichbrodt

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [X] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [X] I have run `npm test` against my changes and tests pass.
- [X] I have added or edited necessary documentation, or no docs changes are needed.

### Description

As discussed, move some docs that were in `Concepts` to more appropriate categories. Some new `Concepts` pages fill in missing concepts. Update links as needed. 

This PR does fill out all known missing docs/feature pages. I did some additional editing for selected `Concepts` docs, but there is more to do to turn them into better feature pages.

2021-03-18 20:37 UTC, timmywil requested changes

2021-03-18 20:37 UTC, timmywil commented on content/blog/building-a-question-answering-bot-with-python/index.md
> +We've included a pre-trained model, so you can follow along with this tutorial, but if you want to create your own, here's a quick introduction to writing NLU training data. See our [documentation](/
URLs no longer have spaces or uppercase letters. It only works for back-compat reasons, and I'd like to remove that in the future.

```suggestion
We've included a pre-trained model, so you can follow along with this tutorial, but if you want to create your own, here's a quick introduction to writing NLU training data. See our [documentation](/docs/machine-learning/nlu-training-data) for more information on our data format and how to train your own model. We are using a basic NLU template which includes intents like `greet`, `accept`, and `help`. In addition, we need a way to identify an entity in the user utterance to perform a Wikipedia search (more on this later). The name of this intent is `ask.question`, and the utterance templates are simple ways to ask a question. Naturally, these templates could be more complex and cover a wider variety of utterances, but for the purpose of this tutorial these will be enough.
```

2021-03-18 20:37 UTC, timmywil commented on content/blog/independence-day/index.md
> +To further that mission to create a complete developer experience for developing voice apps, we're excited that now you can [export your smart speaker skill](/docs/Integrations/export) to run on-devi
```suggestion
To further that mission to create a complete developer experience for developing voice apps, we're excited that now you can [export your smart speaker skill](/docs/integrations/export) to run on-device in the major mobile platforms, and declare your independence as an independent voice assistant from smart speakers!
```

2021-03-18 20:37 UTC, timmywil commented on content/blog/integrating-spokestack-google-app-actions-2/index.md
> +We're going to exploit that similarity and convert our XML directly into Spokestack's [NLU format](/docs/Machine Learning/nlu-training-data), using it to create a custom NLU model that will replicate
```suggestion
We're going to exploit that similarity and convert our XML directly into Spokestack's [NLU format](/docs/machine-learning/nlu-training-data), using it to create a custom NLU model that will replicate the features we've just defined for Google Assistant in our app itself. This is a great opportunity to add new intents to your in-app NLU that would be too tricky or infeasible to expose via Google Assistant.
```

2021-03-18 20:37 UTC, timmywil commented on content/blog/integrating-spokestack-google-app-actions-2/index.md
> +In Spokestack's format, you can achieve the same effect as Google's conditionals (the parenthetical words and question marks in the XML) using [generators](/docs/Machine Learning/nlu-training-data#ge
```suggestion
In Spokestack's format, you can achieve the same effect as Google's conditionals (the parenthetical words and question marks in the XML) using [generators](/docs/machine-learning/nlu-training-data#generators). We've added a few more utterances to the Spokestack config than were present in `actions.xml` because they're a little easier to express here.
```

2021-03-18 20:37 UTC, timmywil commented on content/blog/integrating-spokestack-google-app-actions-2/index.md
> +- `populateVoiceMaps` does a simple synonym mapping of potential slot values (what the user might actually _say_) to canonical device names — in this case, we're actually mapping straight to the UI c
```suggestion
- `populateVoiceMaps` does a simple synonym mapping of potential slot values (what the user might actually _say_) to canonical device names — in this case, we're actually mapping straight to the UI components that represent those devices. This is because Google only lets us specify parameters for custom intents as plain text, rather than allowing the full expressive power of [entities](https://developers.google.com/assistant/app/action-schema#entity) that's available to built-in intents. Hence, we can't do that normalization in `actions.xml`. In Spokestack's format, we can fix this using a [selset slot](/docs/machine-learning/nlu-training-data/selset), but since user queries could come from either Google or Spokestack, we've left the parsing logic in the app so both query types can be handled the same way.
```

2021-03-18 20:37 UTC, timmywil commented on content/blog/integrating-spokestack-in-ios/index.md
> +But if the user initiated the interaction and said, “Search for bananas”, the NLU can parse that statement into an intent (e.g. “search”) with variables (e.g. “bananas”). If you were only using ASR,
```suggestion
But if the user initiated the interaction and said, “Search for bananas”, the NLU can parse that statement into an intent (e.g. “search”) with variables (e.g. “bananas”). If you were only using ASR, you’d probably end up searching for the whole sentence, “search for bananas”, rather than just “bananas”, which may yield different results. For more information on NLU in Spokestack, please check out [our guide](/docs/Concepts/nlu). If you’ve already built an NLU model in Alexa, Dialogflow, or Jovo, check out [our guide on exporting existing NLU models from other platforms](/docs/integrations/export).
```

2021-03-18 20:37 UTC, timmywil commented on content/blog/integrating-spokestack-in-react-native/index.md
> +But if the user initiated the interaction and said, "Search for bananas", the NLU can parse that statement into an intent (e.g. "search") with variables (e.g. "bananas"). If you were only using ASR,
```suggestion
But if the user initiated the interaction and said, "Search for bananas", the NLU can parse that statement into an intent (e.g. "search") with variables (e.g. "bananas"). If you were only using ASR, you'd probably end up searching for the whole sentence, "search for bananas", rather than just "bananas", which may yield different results. For more information on NLU in Spokestack, please check out [our guide](/docs/Concepts/nlu). If you've already built an NLU model in Alexa, Dialogflow, or Jovo, check out [our guide on exporting existing NLU models from other platforms](/docs/integrations/export).
```

2021-03-18 20:37 UTC, timmywil commented on content/blog/introducing-the-spokestack-python-library/index.md
> +Got an Alexa or Google Assistant app you want to set up as a kiosk? Now you can build one on a low-energy, small-form device such as a Raspberry Pi or [Tinker Board](https://www.asus.com/us/Single-Bo
```suggestion
Got an Alexa or Google Assistant app you want to set up as a kiosk? Now you can build one on a low-energy, small-form device such as a Raspberry Pi or [Tinker Board](https://www.asus.com/us/Single-Board-Computer/Tinker-Board/). Maybe you want to set up something on an old PC with a mic and a speaker. Simply [export your NLU model](/docs/integrations/export), and you can do it!
```

2021-03-18 20:37 UTC, timmywil commented on content/blog/porting-a-smart-speaker-voice-app-to-mobile-part-3/index.md
> +To get started with a free NLU model that’s compatible with Spokestack, [create a free account](/create) and upload your existing Alexa or Dialogflow interaction model. The following instructions for
```suggestion
To get started with a free NLU model that’s compatible with Spokestack, [create a free account](/create) and upload your existing Alexa or Dialogflow interaction model. The following instructions for that process are paraphrased from our [export guide](/docs/integrations/export):
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Android/getting-started.md
> +- [converting an Alexa or Dialogflow NLU model](/docs/Integreations/export)
```suggestion
- [converting an Alexa or Dialogflow NLU model](/docs/integreations/export)
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Android/turnkey-configuration.md
> +Once a user's speech has been transcribed, it's useful to know what to _do_ with it. That's where [Natural Language Understanding](nlu) comes in. You'll need an NLU model and supporting files to use
```suggestion
Once a user's speech has been transcribed, it's useful to know what to _do_ with it. That's where [Natural Language Understanding](nlu) comes in. You'll need an NLU model and supporting files to use this feature; see our [model export guide](/docs/integrations/export) for some easy ways to create your own. You'll supply the `Spokestack` builder with paths to these files just like you would wakeword files:
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/asr.md
> +In software using voice powered by Spokestack, ASR is part of the [speech pipeline](/docs/Concepts/speech-pipeline).
```suggestion
In software using voice powered by Spokestack, ASR is part of the [speech pipeline](/docs/concepts/speech-pipeline).
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/index.md
> +A smooth voice experience requires several different pieces of technology working together. The three primary systems involved are [ASR](/docs/Concepts/asr) and [Keyword](/docs/Concepts/keyword), whi
```suggestion
A smooth voice experience requires several different pieces of technology working together. The three primary systems involved are [ASR](/docs/concepts/asr) and [Keyword](/docs/concepts/keyword), which convert user speech into text; [Natural Language Understanding](/docs/concepts/nlu), which translates phrases and sentences into actionable input for an application; and [Text to Speech](/docs/concepts/tts), which converts textual system responses into audio to be read to the user.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/index.md
> +These pages exist to introduce, in a platform-indepedent way, how Spokestack uses these technologies and lets you configure them. They also cover general topics like [converting an NLU model](/docs/I
```suggestion
These pages exist to introduce, in a platform-indepedent way, how Spokestack uses these technologies and lets you configure them. They also cover general topics like [converting an NLU model](/docs/integrations/export) from other voice assistant platforms into Spokestack's format and even how to [design custom wakeword models](/docs/concepts/wakeword-models) for use with Spokestack.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/keywords.md
> +Keyword detection straddles the line between [wake word detection](/docs/Concepts/wakeword) and [speech recognition](/docs/Concepts/asr), with the performance of the former and the results of the lat
```suggestion
Keyword detection straddles the line between [wake word detection](/docs/concepts/wakeword) and [speech recognition](/docs/concepts/asr), with the performance of the former and the results of the latter. A keyword model is trained to recognize a list of named _classes_, each of which may comprise multiple utterances. When the model detects the presence of a class in user speech, it returns the name of the class as a transcript.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/keywords.md
> +The main use case for keyword models is in domains with limited vocabularies or apps that only wish to support specific words or phrases. If users are expected to interact with an app in complete sen
```suggestion
The main use case for keyword models is in domains with limited vocabularies or apps that only wish to support specific words or phrases. If users are expected to interact with an app in complete sentences, or you want to support phrasings you didn't anticipate at build time, a [speech recognition](/docs/concepts/asr) component paired with [natural language understanding](/docs/concepts/nlu) would be a better fit for your case.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/speech-pipeline.md
> +[Voice activity detection](/docs/Concepts/vad) enables the pipeline to listen to small segments of audio and determine if speech is present. To keep computation usage low for edge devices, the rest o
```suggestion
[Voice activity detection](/docs/concepts/vad) enables the pipeline to listen to small segments of audio and determine if speech is present. To keep computation usage low for edge devices, the rest of the pipeline does not proceed if the VAD does not detect speech.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/speech-pipeline.md
> +[A wake word](/docs/Concepts/wake-word) enables the pipeline to listen to speech audio and determine if a name from a set of recognized names is spoken. This fulfills two objectives: one, only listen
```suggestion
[A wake word](/docs/concepts/wake-word) enables the pipeline to listen to speech audio and determine if a name from a set of recognized names is spoken. This fulfills two objectives: one, only listen in on a conversation if the wake word is being spoken, and two preserve the higher-cost ASR component to transcribe only when the user wants to talk.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/speech-pipeline.md
> +When Spokestack detects a wake word, the speech pipeline begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activation time limit elapses. The tech
```suggestion
When Spokestack detects a wake word, the speech pipeline begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activation time limit elapses. The technology for converting spoken words to text is known as [automatic speech recognition (ASR)](/docs/concepts/asr).
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/speech-pipeline.md
> +The speech pipeline is the first piece of the puzzle in any voice interaction and is responsible for capturing user audio and translating it into text. Configuring it entails choices about whether or
```suggestion
The speech pipeline is the first piece of the puzzle in any voice interaction and is responsible for capturing user audio and translating it into text. Configuring it entails choices about whether or not to use a wakeword to activate ASR, what kind of preprocessing to perform on audio before sending it to ASR, and which ASR service to use. These choices can all be made [individually or through the use of configuration profiles](/docs/machine-learning/pipeline-configuration).
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/vad.md
> +VAD is the first gatekeeper in a speech detection pipeline. Ignoring audio that's not detected as speech saves processing power, and the savings grow with each downstream processor you have in your s
```suggestion
VAD is the first gatekeeper in a speech detection pipeline. Ignoring audio that's not detected as speech saves processing power, and the savings grow with each downstream processor you have in your speech pipeline. The Spokestack [speech pipeline](/docs/concepts/speech-pipeline) is a [soft real-time](https://en.wikipedia.org/wiki/Real-time_computing#Criteria_for_real-time_computing) system and its components must be as responsive as possible. It's worse for a downstream component to miss user speech than to process too much, so our VADs tend to err on the side of producing false positives rather than rejecting actual speech.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/wake-word.md
> +When Spokestack detects a wake word, [the speech pipeline](/docs/Concepts/speech-pipeline) begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activ
```suggestion
When Spokestack detects a wake word, [the speech pipeline](/docs/concepts/speech-pipeline) begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activation time limit elapses.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/wake-word.md
> +Spokestack's wake word detectors use a series of three neural models to filter user speech to isolate the most important frequency components, encode those for classification, and detect the presence
```suggestion
Spokestack's wake word detectors use a series of three neural models to filter user speech to isolate the most important frequency components, encode those for classification, and detect the presence of a wake word in the encoded version. More detailed information about the models themselves can be found [in our documentation](/docs/machine-learning/wakeword-models).
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Concepts/wake-word.md
> +A wake word model can be trained to recognize a number of different utterances, so your app can respond to different invocations, but the different utterances will simply activate the speech pipeline
```suggestion
A wake word model can be trained to recognize a number of different utterances, so your app can respond to different invocations, but the different utterances will simply activate the speech pipeline; you won't know which one the user spoke. This contrasts with a [keyword recognizer](/docs/concepts/keywords), which will give you a transcript of the user's speech.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Integrations/nlu-export.md
> +See the documentation on [our training format](/docs/Machine Learning/nlu-training-data) for a way to create a model from scratch.
```suggestion
See the documentation on [our training format](/docs/machine-learning/nlu-training-data) for a way to create a model from scratch.
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/Python/getting-started.md
> +- [converting an Alexa or Dialogflow NLU model](/docs/Integrations/export)
```suggestion
- [converting an Alexa or Dialogflow NLU model](/docs/integrations/export)
```

2021-03-18 20:37 UTC, timmywil commented on content/docs/iOS/getting-started.md
> +Go to [spokestack.io](/account/) to set up your own account (it's free!). Once you've got that, go [grab one of our free NLU models](/account/services/nlu). We'll use the `Highlow` one in this exampl
```suggestion
Go to [spokestack.io](/account/) to set up your own account (it's free!). Once you've got that, go [grab one of our free NLU models](/account/services/nlu). We'll use the `Highlow` one in this example, but you can choose another, or [create your own](/docs/integrations/export) if you already have something on DialogFlow or Alexa!
```

2021-03-19 13:25 UTC, space-pope reviewed
"Does fill out" or "doesn't fill out" all known features? I know there were a few items on the original doc that didn't make it into pages here, but wasn't sure if we'd just decided to drop those.

I was in the middle of a review when the first batch of corrections came in, and when I refreshed, GitHub hid some of my comments from me, so apologies if there are duplicates—a few of the ones that'll already be marked "outdated" are actually still relevant; they just covered a line that had another change made to it.

2021-03-19 13:25 UTC, space-pope commented on content/blog/building-a-question-answering-bot-with-python/index.md
> +We've included a pre-trained model, so you can follow along with this tutorial, but if you want to create your own, here's a quick introduction to writing NLU training data. See our [documentation](/
```suggestion
We've included a pre-trained model so you can follow along with this tutorial, but if you want to create your own, here's a quick introduction to writing NLU training data. See our [documentation](/docs/Machine Learning/nlu-training-data) for more information on our data format and how to train your own model. We are using a basic NLU template which includes intents like `greet`, `accept`, and `help`. In addition, we need a way to identify an entity in the user utterance to perform a Wikipedia search (more on this later). The name of this intent is `ask.question`, and the utterance templates are simple ways to ask a question. Naturally, these templates could be more complex and cover a wider variety of utterances, but for the purpose of this tutorial these will be enough.
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Android/getting-started.md
> +- [converting an Alexa or Dialogflow NLU model](/docs/Integreations/export)
```suggestion
- [converting an Alexa or Dialogflow NLU model](/docs/integrations/export)
```
...though I have to admit I'll miss our integreations. They were...not bad.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/asr.md
> +Automatic speech recognition (ASR) refers to the process of analyzing and transcribing a chunk of audio without human intervention. This technology is ubiquitous, with a place in the stack of every m
```suggestion
ASR refers to the process of analyzing and transcribing a chunk of audio without human intervention. This technology is ubiquitous, with a place in the stack of every major voice assistant on the market.
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/asr.md
> +Accuracy is often measured in Word Error Rate (WER), or the percentage of words that differ between the ASR system's transcript and that of a gold-standard version. Getting an accurate WER measuremen
```suggestion
Accuracy is often measured in Word Error Rate (WER), or the percentage of words that differ between the ASR system's transcript and that of a gold-standard version. Getting an accurate WER measurement entails juggling many different variables (think accent, background noise, whether we're talking about a speech vs. a multi-party conversation, etc.), and it's [easy to spin](https://arxiv.org/abs/2010.03432). There are, however, various [academic comparisons](https://www.aclweb.org/anthology/2020.lrec-1.797.pdf) of major vendors. For perspective, human WER hovers [somewhere between 4-11%](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/06/paper-revised2.pdf), depending on variables like those mentioned above, usually falling on the lower end of that range.
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/index.md
> +A smooth voice experience requires several different pieces of technology working together. The three primary systems involved are [ASR](/docs/Concepts/asr) and [Keyword](/docs/Concepts/keyword), whi
This is confusing. Keyword is a type of ASR, so "ASR _and_ keyword" doesn't make much sense to me. It's definitely not a different system. If we do want to introduce it at the top level, I think it deserves its own sentence/paragraph somewhere.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/keywords.md
> +Keyword detection straddles the line between [wake word detection](/docs/Concepts/wakeword) and [speech recognition](/docs/Concepts/asr), with the performance of the former and the results of the lat
This paragraph mostly duplicates the previous one; they could be combined.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/keywords.md
> +### Personal keyword
I thought we were going with headline case for section headers (or is that just h2s?). Might want to check the other pages for this too if so.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/speech-pipeline.md
> +The speech pipeline is the main way you interact with Spokestack’s VAD, wake word, and speech recognition. The speech pipeline is an extensible audio processing pipeline that includes a variety of bu
```suggestion
The speech pipeline is the main way you interact with Spokestack’s voice activity detection (VAD), wake word detection, and automatic speech recognition (ASR). The speech pipeline is an extensible audio processing pipeline that includes a variety of built-in speech processors for all the above stages.
```
Do we want to link to the concept pages here too?

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/speech-pipeline.md
> +This pipeline seamlessly integrates VAD-triggered wake word detection using on-device machine learning models with transcribing utterances using ASR. It runs as a [soft real-time](https://en.wikipedi
```suggestion
This pipeline seamlessly integrates VAD-triggered wake word detection using on-device machine learning models with speech transcription. It runs as a [soft real-time](https://en.wikipedia.org/wiki/Real-time_computing#Criteria_for_real-time_computing) system, and its components must be as responsive as possible.
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/speech-pipeline.md
> +[A wake word](/docs/Concepts/wake-word) enables the pipeline to listen to speech audio and determine if a name from a set of recognized names is spoken. This fulfills two objectives: one, only listen
```suggestion
[A wake word](/docs/concepts/wake-word) enables the pipeline to listen to speech audio and determine if a name from a set of recognized names is spoken. This fulfills two objectives: one, only listen in on a conversation if the wake word is being spoken; and two, ensure the higher-cost ASR component to runs only when the user wants to be understood by an app.
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/speech-pipeline.md
> +When Spokestack detects a wake word, the speech pipeline begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activation time limit elapses. The tech
```suggestion
When Spokestack detects a wake word, the speech pipeline begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activation time limit elapses. The technology for converting spoken words to text is known as [automatic speech recognition](/docs/concepts/asr).
```
We don't need to reintroduce the initialism, but using the full phrase makes sense here.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/speech-pipeline.md
> +The speech pipeline is the first piece of the puzzle in any voice interaction and is responsible for capturing user audio and translating it into text. Configuring it entails choices about whether or
```suggestion
The speech pipeline is the first piece of the puzzle in any voice interaction and is responsible for capturing user audio and translating it into text. Configuring it entails choices about whether or not to use a wake word to activate ASR, what kind of preprocessing to perform on audio before sending it to ASR, and which ASR service to use. These choices can all be made [individually or through the use of configuration profiles](/docs/machine-learning/pipeline-configuration).
```
Starting a final paragraph with "the first piece of the puzzle" without further elaboration on that feels a little odd to me.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Android/getting-started.md
> +- [converting an Alexa or Dialogflow NLU model](/docs/integreations/export)
```suggestion
- [converting an Alexa or Dialogflow NLU model](/docs/integrations/export)
```

2021-03-19 13:25 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +But if the user initiated the interaction and said, "Search for bananas", the NLU can parse that statement into an intent (e.g. "search") with variables (e.g. "bananas"). If you were only using ASR,
```suggestion
But if the user initiated the interaction and said, "Search for bananas", the NLU can parse that statement into an intent (e.g. "search") with variables (e.g. "bananas"). If you were only using ASR, you'd probably end up searching for the whole sentence, "search for bananas", rather than just "bananas", which may yield different results. For more information on NLU in Spokestack, please check out [our guide](/docs/concepts/nlu). If you've already built an NLU model in Alexa, Dialogflow, or Jovo, check out [our guide on exporting existing NLU models from other platforms](/docs/integrations/export).
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/speech-pipeline.md
> +When Spokestack detects a wake word, the speech pipeline begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activation time limit elapses. The tech
```suggestion
When Spokestack detects a wake word, the speech pipeline begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activation time limit elapses. The technology for converting spoken words to text is known as [automatic speech recognition](/docs/concepts/asr).
```
We've already introduced the initialism, but it does make sense to use the full form here.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/speech-pipeline.md
> +The speech pipeline is the first piece of the puzzle in any voice interaction and is responsible for capturing user audio and translating it into text. Configuring it entails choices about whether or
Starting a final paragraph with "the first piece of the puzzle" without any further talk of the puzzle seems odd to me.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/vad.md
> +Voice Activity Detection, or VAD, is responsible for makes a quick, low-cost determination of whether a snippet of audio contains human speech or not.
```suggestion
Voice activity detection, or VAD, is responsible for making a quick, low-cost determination of whether a snippet of audio contains human speech.
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/vad.md
> +VAD is the first gatekeeper in a speech detection pipeline. Ignoring audio that's not detected as speech saves processing power, and the savings grow with each downstream processor you have in your s
```suggestion
VAD is the first gatekeeper in a speech detection pipeline. Ignoring audio that's not detected as speech saves processing power, and the savings grow with each downstream processor you have in your speech pipeline. The Spokestack [speech pipeline](/docs/concepts/speech-pipeline) is a [soft real-time](https://en.wikipedia.org/wiki/Real-time_computing#Criteria_for_real-time_computing) system, and its components must be as responsive as possible. It's worse for a downstream component to miss user speech than to process too much, so our VADs tend to err on the side of producing false positives rather than rejecting actual speech.
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/wake-word.md
> +A wakeword is a signal for the computer to begin transitioning from passive to active listening. It acts as your software's "name", signaling that the user is speaking to the app. “Hey Siri” and “Ale
```suggestion
A wake word is a signal for the computer to begin transitioning from passive to active listening. It acts as your software's "name", signaling that the user is speaking to the app. “Hey Siri” and “Alexa” are two of the most widely known wake words.
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/wake-word.md
> +When Spokestack detects a wake word, [the speech pipeline](/docs/concepts/speech-pipeline) begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activ
```suggestion
When Spokestack detects a wake word, the [speech pipeline](/docs/concepts/speech-pipeline) begins transcribing the user's speech until they stop talking for a pre-set amount of time, or a total activation time limit elapses.
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Concepts/wake-word.md
> +Spokestack's personal wake word uses few-shot transfer learning, allowing a small amount of data to produce a neural model with an accuracy level suitable for personal, hobby, or exploratory projects
Since we link to the account section in other docs, should the "personal ..." section in wakeword/keyword link to those pages in the Maker account, perhaps mentioning that the reader will need a Maker-tier account or higher to use them?

2021-03-19 13:25 UTC, space-pope commented on content/docs/Machine Learning/pipeline-configuration.md
> +title: Wakeword
```suggestion
title: Speech Pipeline Configuration
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/nav.json
> +  "Speech Pipeline Models (Machine Learning)",
```suggestion
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/Machine Learning/pipeline-configuration.md
>  tags: ASR, Wakeword
The Wakeword tag should probably be changed to "Wake Word" across the board.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Machine Learning/pipeline-configuration.md
>  tags: ASR, Wakeword
There are also a couple instances of "wakeword" on this page that should change.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Machine Learning/wakeword-models.md
> +navId: Wake Word Models (Machine Learning)
A couple instances of "wakeword" below here too; I just can't do line-by-line comments because the lines haven't been changed.

2021-03-19 13:25 UTC, space-pope commented on content/docs/Python/getting-started.md
> +Go to [spokestack.io](/create) to set up your own account (it's free!). Once you've got that, go [grab one of our free NLU models](/account/services/nlu). We'll use the `Highlow` one in this example,
```suggestion
Go to [spokestack.io](/create) to set up your own account (it's free!). Once you've got that, go [grab one of our free NLU models](/account/services/nlu). We'll use the `Highlow` one in this example, but you can choose another, or [create your own](/docs/machine-learning/nlu-training-data)
```

2021-03-19 13:25 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +Go to [spokestack.io](/account/) to set up your own account (it's free!). Once you've got that, go [grab one of our free NLU models](/account/services/nlu). We'll use the `Highlow` one in this exampl
The "create your own" link in the Python getting started guide points to the training data explanation; this one points to the export page (I think Android does too). We should probably make those consistent.

2021-03-19 13:25 UTC, space-pope commented on content/docs/nav.json
> +  "Speech Pipeline (Concepts)",
Should we order the concept guides according to the rough order that data gets processed? So maybe "speech pipeline" first to introduce things, then vad, wakeword, etc.?

2021-03-19 13:43 UTC, noelweichbrodt commented
Wording was confusing, apologies—meant that this (should) adds all the features from that docs that are before "Maker".

2021-03-19 16:17 UTC, timmywil approved these changes

2021-03-19 16:39 UTC, timmywil commented on content/docs/Concepts/wake-word.md
> +Your [Spokestack Maker account](/account#billing) gives you the ability to create a personal wake word using few-shot transfer learning, allowing a small amount of data to produce a neural model with
`/account#billing` will be moved to `/account/settings#billing` when the welcome page is merged.

2021-03-19 16:39 UTC, timmywil commented on content/docs/Concepts/wake-word.md
> +Your [Spokestack Maker account](/account#billing) gives you the ability to create a personal wake word using few-shot transfer learning, allowing a small amount of data to produce a neural model with
I'm going to audit all `/account` links later tho.

2021-03-19 19:50 UTC, roppem9 commented on content/docs/Concepts/keywords.md
> +### Personal keyword
I've been using Wikipedia style for title casing newsletter headlines - it'd be nice if we could keep using that style for all headers going forward. This tool is useful: https://titlecaseconverter.com/

2021-03-19 19:51 UTC, roppem9 commented on content/docs/Machine Learning/pipeline-configuration.md
>  tags: ASR, Wakeword
Agreed. I think we agreed to go with "wake word" two words - we'll need to update that throughout the site

2021-03-19 19:51 UTC, roppem9 commented on content/docs/nav.json
> +  "Speech Pipeline (Concepts)",
Makes sense to me

2021-03-19 19:52 UTC, roppem9 approved these changes

2021-03-19 20:21 UTC, roppem9 commented on content/docs/nav.json
>    "Spokestack Configuration (Android)",
I would either include "Spokestack Tray" in place of every instance of "Tray" or change "Spokestack Configuration" in Android to just "Configuration"

2021-03-19 20:53 UTC, timmywil commented on content/docs/nav.json
>    "Spokestack Configuration (Android)",
This is just the nav id, a unique name for ordering. The title is set in the docs pages themselves, and this one is "Spokestack Tray".

2021-03-19 20:54 UTC, timmywil commented on content/docs/Machine Learning/pipeline-configuration.md
>  tags: ASR, Wakeword
That can be a separate PR btw.

2021-03-19 21:03 UTC, space-pope reviewed
Sorry. Can't help rereading things...

2021-03-19 21:03 UTC, space-pope commented on content/docs/Android/tray.md
> +[Spokestack Tray](/docs/concepts/tray) for Android is a `Fragment` component library that quickly and easily adds voice interaction to any Android app. Get started from the simple [instructions on Gi
```suggestion
[Spokestack Tray](/docs/concepts/tray) for Android is a UI library that quickly and easily adds voice interaction to any Android app. Get started from the simple [instructions on Github](https://github.com/spokestack/spokestack-tray-android/#usage)! Manage voice interactions for your app, delivering actionable user commands with the help of Spokestack Tray in just a few lines of code!
```

2021-03-19 21:03 UTC, space-pope commented on content/docs/Concepts/asr.md
> +The technology for converting spoken words to text is known as automatic speech recognition (ASR).
Does this add to the following paragraph?

2021-03-19 21:03 UTC, space-pope commented on content/docs/Concepts/asr.md
> +In software using voice powered by Spokestack, ASR is part of the [speech pipeline](/docs/concepts/speech-pipeline).
protip: it's not really necessary to change this, but when you're linking to a doc in the same folder, you can skip the `/docs/concepts/` prefix.

2021-03-19 21:03 UTC, space-pope commented on content/docs/Concepts/index.md
> +A smooth voice experience requires several different pieces of technology working together. The three primary systems involved are the [speech pipeline](/docs/concepts/speech-pipeline), responsible f
```suggestion
A smooth voice experience requires several different pieces of technology working together. The three primary systems involved are the [speech pipeline](/docs/concepts/speech-pipeline), responsible for listening to the user and converting their speech into text; [Natural Language Understanding](/docs/concepts/nlu), which translates phrases and sentences into actionable input for an application; and [Text to Speech](/docs/concepts/tts), which converts textual system responses into audio to be read to the user.
```

2021-03-19 21:03 UTC, space-pope commented on content/docs/Concepts/index.md
> +These pages exist to introduce, in a platform-indepedent way, how Spokestack uses these technologies and lets you configure them. They also cover general topics like [converting an NLU model](/docs/i
_pushes glasses up_ Technically, the NLU model conversion is no longer a part of "these pages" since it's been moved to the new "integrations" section.

2021-03-19 21:03 UTC, space-pope commented on content/docs/Concepts/keywords.md
> +Keyword recognition detects words or phrases from a list of key words. You define that list of words, and Spokestack notifies your software when any of them are recognized. This detection happens ent
```suggestion
Keyword recognition detects words or phrases from a list of key words. You define that list of words, and Spokestack notifies your software when any of them is recognized. This detection happens entirely on-device, with no data going over the network or to the cloud. Keyword detection straddles the line between [wake word detection](/docs/concepts/wakeword) and [speech recognition](/docs/concepts/asr), with the performance of the former and the results of the latter. Each keyword may comprise multiple utterances. When the model detects the presence of an utterance in user speech, it returns the keyword as a transcript.
```

2021-03-19 21:03 UTC, space-pope commented on content/docs/Concepts/speech-pipeline.md
> +This pipeline seamlessly integrates VAD-triggered wake word detection using on-device machine learning models with speech transcription. It runs as a [soft real-time](https://en.wikipedia.org/wiki/Re
```suggestion
This pipeline seamlessly integrates VAD-triggered wake word detection using on-device machine learning models with speech transcription. It runs as a [soft real-time](https://en.wikipedia.org/wiki/Real-time_computing#Criteria_for_real-time_computing) system.
```
I know I wrote this, but I'm having second thoughts—including "as responsive as possible" is both hand-wavey and more of a guideline for developing a new pipeline stage; I think we can just cut the sentence off earlier.

2021-03-19 21:03 UTC, space-pope commented on content/docs/Concepts/tray.md
> +Few mobile developers understand how to design conversational experiences. And few voice developers know how to build mobile apps. At Spokestack, we’re hoping to nudge both sides closer to each other
I like these last two paragraphs.

2021-03-19 21:03 UTC, space-pope commented on content/docs/Concepts/vad.md
> +description: Documentation for Spokestack's third-party ASR support
```suggestion
description: Understanding Spokestack's voice activity detector
```

2021-03-19 21:03 UTC, space-pope commented on content/docs/Concepts/wake-word.md
> +description: Understanding Wake Words
```suggestion
description: Understanding wake words
```
The description gets pulled out as a tagline in search results, right? I think these tend to be closer to sentences than headlines.

2021-03-19 21:03 UTC, space-pope commented on content/docs/React Native/tray.md
> +[Spokestack Tray](/docs/concepts/tray) for React Native is a UI component library that quickly and easily adds voice interaction to any React Native app. Get started from the simple [instructions on
```suggestion
[Spokestack Tray](/docs/concepts/tray) for React Native is a UI component library that quickly and easily adds voice interaction to any React Native app. Get started from the simple [instructions on Github](https://github.com/spokestack/react-native-spokestack-tray#installation)! Manage voice interactions for your app, delivering actionable user commands with the help of Spokestack Tray in just a few lines of code!
```

2021-03-19 21:03 UTC, space-pope commented on content/docs/iOS/tray.md
> +[Spokestack Tray](/docs/concepts/tray) for iOS is a SwiftUI component library that quickly and easily adds voice interaction to any iOS app. Get started from the simple [instructions on Github!](http
```suggestion
[Spokestack Tray](/docs/concepts/tray) for iOS is a SwiftUI component library that quickly and easily adds voice interaction to any iOS app. Get started from the simple [instructions on Github](https://github.com/spokestack/spokestack-tray-ios#installation)! Manage voice interactions for your app, delivering actionable user commands with the help of Spokestack Tray in just a few lines of code!
```

2021-03-19 21:03 UTC, space-pope commented on content/docs/nav.json
> +  "Tray (iOS)",
It seems a little odd to me to not have "getting started" be the first doc in each platform. I get the intent, but wonder if preserving the expectation of "start" is more important.

I think ideally, the concepts page for Tray should be the introduction to the concept, and the page under each platform goes into particulars about using/configuring the tray on that platform, so it's a more in-the-weeds thing rather than an invitation to the github repo as a way to integrate Spokestack.

2021-03-19 21:45 UTC, noelweichbrodt commented
> I think ideally, the concepts page for Tray should be the introduction to the concept, and the page under each platform goes into particulars about using/configuring the tray on that platform, so it's a more in-the-weeds thing rather than an invitation to the github repo as a way to integrate Spokestack.

Agreed, this is just v1 for the platform tray pages. should be revised next as per your suggestion.

2021-03-19 21:53 UTC, merged