fix(docs): various doc updates
spokestack/spokestack-website pull request #203
Opened 2021-06-15 19:18 UTC by space-pope

- add intra-site links
- add more info on keyword recognition in RN
- replace missing speech pipeline state diagram

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [x] I have run `npm test` against my changes and tests pass.
- [x] I have added or edited necessary documentation, or no docs changes are needed.

### Description

I bounced around a bit and found a few different minor updates to make:

- added intra-site links
- added more info on keyword recognition in RN
- replaced missing speech pipeline state diagram

I'm a little unclear on whether we should prefer to link to `/pricing#maker` or `account/billing` for Maker CTAs—the former seems more user-friendly (it's prettier), but the latter also includes an upgrade CTA, and it saves the user a trip to the pricing page if they're already a subscriber. I've left some of those links inconsistent here—thoughts?

2021-06-16 16:16 UTC, timmywil commented on content/docs/Android/speech-pipeline.md
> +![speech pipeline](../../assets/docs/speech_pipeline_states.png 'speech pipeline')
Can remove the `'speech pipeline'` at the end. What's important is to set the alt attribute in the square brackets.

2021-06-16 16:18 UTC, timmywil approved these changes
LGTM

2021-06-16 16:19 UTC, timmywil commented
I guess I'd like to pricing instead of account. Has more explanation text. Could also link to `/account/upgrade`, but that won't always apply.

2021-06-16 16:40 UTC, noelweichbrodt requested changes
`account/billing` should actually be `/account/settings#billing`, but for maker CTAs we should be using `account/upgrade`, which is in the middle of a redesign that will create the best signup flow yet.

2021-06-16 16:40 UTC, noelweichbrodt commented on content/blog/what-are-personal-ai-models/index.md
> +The [Spokestack Maker](/pricing#maker) service is designed for two audiences: (1) hobbyists who want to personalize their projects, and (2) developers who want to prototype a project as realistically
```suggestion
The [Spokestack Maker](/account/upgrade) service is designed for two audiences: (1) hobbyists who want to personalize their projects, and (2) developers who want to prototype a project as realistically as possible before committing to training a universal wake word model or studio-quality text-to-speech (TTS) voice. This is a great way to test drive the technology without breaking the bank.
```

2021-06-16 16:40 UTC, noelweichbrodt commented on content/docs/Android/turnkey-configuration.md
> +[detect](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/detect.tflite) | [encode](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/encode.tflite) | [filter](https://d3dmqd7cy6
```suggestion
[detect](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/detect.tflite) | [encode](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/encode.tflite) | [filter](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/filter.tflite)

For more pre-trained wake words, and to make your own custom wake words, [create your free Spokestack account!](account/create)
```

2021-06-16 16:40 UTC, noelweichbrodt commented on content/docs/React Native/cookbook.md
> +You can also [use local model files](require-models) if you want to avoid a runtime download. This sample uses the free "Spokestack" wake word. To create a custom wake word, try our [Maker subscripti
```suggestion
You can also [use local model files](require-models) if you want to avoid a runtime download. This sample uses the free "Spokestack" wake word. To create a custom wake word, try our [Maker subscription](/account/upgrade).
```

2021-06-16 16:40 UTC, noelweichbrodt commented on content/docs/React Native/cookbook.md
> +[Keyword recognition](/docs/concepts/keywords) is a type of ASR that responds only to a pre-configured vocabulary. This sample uses a free keyword recognition model that recognizes the English numera
```suggestion
[Keyword recognition](/docs/concepts/keywords) is a type of ASR that responds only to a pre-configured vocabulary. This sample uses a free keyword recognition model that recognizes the English numerals "zero" through "nine". To create a custom model, try our [Maker subscription](/account/upgrade).
```

2021-06-16 16:40 UTC, noelweichbrodt commented on content/docs/Concepts/tts.md
> +Spokestack offers a rich, controllable text-to-speech (TTS) system. The voices available to use in your app are determined by your API client identifier, but we offer a demo voice to all users so tha
```suggestion
Spokestack offers a rich, controllable text-to-speech (TTS) system. The voices available to use in your app are determined by your API client identifier, but we offer a demo voice to all users so that you can try custom TTS in your app without making a commitment. If you need a unique voice for your project, our [Maker tier](/account/upgrade) lets you create your own! If you'd like a custom voice created from studio-quality recordings, [contact us](mailto:hello@spokestack.io), and we can work with you to create a unique experience for your users.
```

2021-06-16 16:40 UTC, noelweichbrodt commented on content/docs/Machine Learning/wakeword-models.md
> +Spokestack provides pretrained [TensorFlow Lite](https://www.tensorflow.org/lite) models that enable on-device wake word detection. These free models, however, only recognize the word "Spokestack"; i
```suggestion
Spokestack provides pretrained [TensorFlow Lite](https://www.tensorflow.org/lite) models that enable on-device wake word detection. These free models, however, only recognize the word "Spokestack"; in order to have your app respond to a different word or phrase, you'll need new models. If machine learning is outside your wheelhouse and you'd like a customized wake word for your app, check out our [Maker tier](/account/upgrade) for a way to prototype a [personal wake word model](/blog/what-are-personal-ai-models), no code required.
```

2021-06-16 16:55 UTC, space-pope commented on content/docs/Android/turnkey-configuration.md
> +[detect](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/detect.tflite) | [encode](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/encode.tflite) | [filter](https://d3dmqd7cy6
Doesn't that sort of imply that creating your own is free too?

2021-06-16 16:56 UTC, space-pope commented
Where will `account/upgrade` redirect to if the reader isn't logged in?

2021-06-16 16:57 UTC, noelweichbrodt commented on content/docs/Android/turnkey-configuration.md
> +[detect](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/detect.tflite) | [encode](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/encode.tflite) | [filter](https://d3dmqd7cy6
an account is necessary but not sufficient to create your own

2021-06-16 16:58 UTC, noelweichbrodt commented
it becomes a regular create an account. once the account is created, it redirects to the upgrade modal

2021-06-16 16:59 UTC, space-pope commented
OK—my next question was why you didn't change _all_ the `pricing` links, but I guess that explains it. It does still seem a little arbitrary when we link to one vs. the other, though.

2021-06-16 17:00 UTC, space-pope commented on content/docs/Android/turnkey-configuration.md
> +[detect](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/detect.tflite) | [encode](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/encode.tflite) | [filter](https://d3dmqd7cy6
_I_ know that, and _you_ know that... 🙂

2021-06-16 17:19 UTC, noelweichbrodt commented
it's just a question of whether the link to create an account, or to use Maker. the former is `/account/create`, the latter is `/account/upgrade`

2021-06-16 17:33 UTC, space-pope commented
In that case, I guess you're saying we _should_ update all the other `pricing` links?

2021-06-16 17:35 UTC, noelweichbrodt commented
I'm not sure contextually where it makes sense, but probably?

2021-06-16 18:58 UTC, timmywil commented
I wouldn't update them all until the upgrade page supports that. For now, I'd keep them all at pricing. Then when we update the upgrade page, we can do a find/replace on the pricing links.

2021-06-17 00:20 UTC, timmywil commented on content/blog/introducing-spokestack-maker/index.md
>  Lowering the barriers to voice technology means reducing technical cost in addition to the sticker shock that custom machine learning models often carry. Voice AI is a difficult field, full of papers
```suggestion
Lowering the barriers to voice technology means reducing technical cost in addition to the sticker shock that custom machine learning models often carry. Voice AI is a difficult field, full of papers with irreproducible results, hidden pitfalls, and undocumented code. You can end up spending all day in Jupyter notebooks babysitting training jobs instead of building your killer app. We know, we’ve done it before! [Spokestack Maker](/pricing#maker) turns voice into just another interface developers utilize—like a mouse & keyboard or a touchscreen—to interact with users.
```

2021-06-17 00:20 UTC, timmywil commented on content/blog/what-are-personal-ai-models/index.md
> +The [Spokestack Maker](/account/upgrade) service is designed for two audiences: (1) hobbyists who want to personalize their projects, and (2) developers who want to prototype a project as realistical
```suggestion
The [Spokestack Maker](/pricing#maker) service is designed for two audiences: (1) hobbyists who want to personalize their projects, and (2) developers who want to prototype a project as realistically as possible before committing to training a universal wake word model or studio-quality text-to-speech (TTS) voice. This is a great way to test drive the technology without breaking the bank.
```

2021-06-17 00:21 UTC, timmywil commented on content/docs/Concepts/tts.md
> +Spokestack offers a rich, controllable text-to-speech (TTS) system. The voices available to use in your app are determined by your API client identifier, but we offer a demo voice to all users so tha
```suggestion
Spokestack offers a rich, controllable text-to-speech (TTS) system. The voices available to use in your app are determined by your API client identifier, but we offer a demo voice to all users so that you can try custom TTS in your app without making a commitment. If you need a unique voice for your project, our [Maker tier](/pricing#maker) lets you create your own! If you'd like a custom voice created from studio-quality recordings, [contact us](mailto:hello@spokestack.io), and we can work with you to create a unique experience for your users.
```

2021-06-17 00:21 UTC, timmywil commented on content/docs/Machine Learning/wakeword-models.md
> +Spokestack provides pretrained [TensorFlow Lite](https://www.tensorflow.org/lite) models that enable on-device wake word detection. These free models, however, only recognize the word "Spokestack"; i
```suggestion
Spokestack provides pretrained [TensorFlow Lite](https://www.tensorflow.org/lite) models that enable on-device wake word detection. These free models, however, only recognize the word "Spokestack"; in order to have your app respond to a different word or phrase, you'll need new models. If machine learning is outside your wheelhouse and you'd like a customized wake word for your app, check out our [Maker tier](/pricing#maker) for a way to prototype a [personal wake word model](/blog/what-are-personal-ai-models), no code required.
```

2021-06-17 15:03 UTC, merged