Feature/docs mdx
spokestack/spokestack-website pull request #208
Opened 2021-06-24 22:07 UTC by timmywil

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _develop_.
- [x] I have run `npm test` against my changes and tests pass.
- [x] I have added or edited necessary documentation, or no docs changes are needed.

### Description

Adds all overview pages to docs, including a global overview page and then one for each platform.

Each overview page has a configurator on it. The configurator was added by switching all markdown parsing from remark to [mdx](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/). This allows us to use jsx-like syntax in markdown and including React components in markdown files.

The nav was also redesigned for the whole docs section, and more related resources were added to all docs pages.

This PR does not include:

- Spotlight testing in the configurator. This will come in a separate PR, but likely after we add Pro.
- Related videos. I'm not sure how to add these. We don't maintain a list of videos with tags on each video. This would likely involve adding lists of videos on each docs page statically, which would be error-prone and just about impossible to maintain. But, I think embedding the videos that pertain to a particular page's subject will be enough and this section isn't really needed anyway.

2021-06-25 17:20 UTC, space-pope commented
I like all the new stuff. Here's what I noticed on first look:

- The markdown rules (`---`) rendering as hyphens looks a bit odd
- I like the changes to the lefthand nav, though the indent is subtle enough that it took me a few looks to see it
- It'd be nice if the configurator were a generic component that we could configure inline rather than a component with a hardcoded set of features to display. i.e., it might be helpful to have an inline configurator that switches between programming languages for a given sample or one that includes a feature not available on all platforms.

I'll add suggestions for the Android stuff in a PR on top of this one.

2021-06-25 17:43 UTC, space-pope commented
Oh, and looks like the configurator can only display one-digit line numbers (they go from `9` to `0`).

2021-06-25 18:03 UTC, timmywil commented
> The markdown rules (---) rendering as hyphens looks a bit odd

I'm not sure what you mean by this. It renders `<hr />` elements.

> it might be helpful to have an inline configurator that switches between programming languages

That sounds different. The configurator is there to showcase platform code in the docs and on feature pages. Sample code can still be prettified on its own. That said, we could have another sample code component that switches between different languages (like Java and Kotlin) on a platform page. But putting the code for this configurator inline would be an awful mess.

> one that includes a feature not available on all platforms

You can set both platform and feature props to limit it to showing just one feature on one platform. It wouldn't be hard to limit a particular feature to 2-3 platforms, which we've done before when node and react native didn't have a speech pipeline yet. But, ideally, the different platforms have feature parity.

2021-06-25 18:14 UTC, space-pope commented
![image](https://user-images.githubusercontent.com/5109003/123468122-5535ef80-d5bf-11eb-9265-1abc480edc99.png)
Guess those are too long to be actual hyphens, but that's how the markdown `---` is rendering for me locally.

And I didn't mean putting the entire configurator inline, but maybe being able to feed the component a list of title/sample code for ad hoc display. A separate sample code component seems like a reasonable middle ground, but I don't have a concrete use case for it in mind yet, so don't think there's any need to actually add one yet.

2021-06-25 18:49 UTC, timmywil commented
ah, that's the new style for `<hr>` elements.

2021-06-25 19:16 UTC, space-pope commented
Gotcha. Just seems a little choppy to me. I think another thing that grabs my eye (which might be a significant part of the "choppiness") is that the `hr`/box border color is the same as the text color in dark mode (which is what I use), but it's more muted relative to the text in light mode. Makes the light mode look a little cleaner IMO.

2021-06-25 19:49 UTC, timmywil commented
Good points. I can update both.

2021-06-25 19:52 UTC, timmywil commented
Everything mentioned should be updated now.

2021-06-25 20:09 UTC, space-pope commented
Awesome! I think the `hr`s could be a _little_ lighter, but that's kind of nitpicking—I like these changes a lot.

It does look like the footer's CSS is coming from somewhere other than the place that changed, though—its `hr`s are still white (almost looks like the box borders are too, but turns out they're not, just thin enough that they almost blend in with the rule).

2021-06-25 20:25 UTC, timmywil commented
I don't know of an `hr` in the footer.

2021-06-25 20:26 UTC, timmywil commented
Oh, you mean in the Related section. Yea, those aren't `hr`'s exactly, but should be lighter.

2021-06-25 20:29 UTC, space-pope commented
Oh, my bad. Forgot those were inline compoents—yeah, that section.

2021-06-25 22:12 UTC, noelweichbrodt reviewed
Looks great! Love the new details like the right-side outline and the redesigned Related footers.

2021-06-25 22:12 UTC, noelweichbrodt commented on src/components/Configurator.tsx
> +  platform?: Platform
if `platform` is specificed, then "Select Feature" should not be shown imo.

2021-06-25 22:14 UTC, timmywil commented on src/components/Configurator.tsx
> +  platform?: Platform
Yea, I considered that. The design shows the header on the platform pages, but we could make it conditional.

2021-06-25 22:16 UTC, noelweichbrodt commented on src/components/Configurator.tsx
> +  platform?: Platform
I think that would be good. It feels redundant on the platform pages, the place we want the eye to fall is on the feature names directly

2021-06-26 16:56 UTC, will-rice approved these changes

2021-06-29 15:54 UTC, will-rice requested changes
I tagged one fix, everything else in Python looks good.

2021-06-29 15:54 UTC, will-rice commented on src/samples/python.ts
> +## ...
we could probably remove `## ...`

2021-06-29 16:11 UTC, will-rice approved these changes
lgtm

2021-06-29 16:13 UTC, merged