Update Getting Started guide
spokestack/spokestack-website pull request #3
Opened 2019-11-15 21:25 UTC by space-pope

It still needs an update or two (pending the completion of one of the APIs), but I thought maybe it'd help to have this for people to look over.

2019-11-16 00:11 UTC, timmywil requested changes
Looks good. Always specify a language so code gets colors.

2019-11-16 00:11 UTC, timmywil commented on content/docs/Getting-Started/index.md
> +```
Specify bash as language.

2019-11-16 00:11 UTC, timmywil commented on content/docs/Getting-Started/index.md
> +```
Same here

2019-11-16 00:11 UTC, timmywil commented on content/docs/Getting-Started/index.md
> +```
Specify xml as language

2019-11-16 00:12 UTC, timmywil commented on content/docs/Getting-Started/index.md
> +```
I'd also remove the extra tabs here.

2019-11-16 01:45 UTC, space-pope commented on content/docs/Getting-Started/index.md
> +```
Good call—and gah; didn't even realize those were actual tabs. Thanks, Xcode.

2019-11-16 01:49 UTC, space-pope commented
Thanks for the syntax check. I sort of didn't think the `bash` would do anything for the CocoaPods commands, but it's a good habit either way.

2019-11-19 00:31 UTC, merged

2019-12-03 19:37 UTC, timmywil commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack-website/releases/tag/1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: