feat(blog): new blog post
spokestack/spokestack-website pull request #48
Opened 2020-03-19 20:40 UTC by miketatum

This is my latest blog post.

2020-03-19 20:56 UTC, timmywil requested changes

2020-03-19 20:56 UTC, timmywil commented on content/blog/keeping-perspective.md
> +description: Spokestack is a powerful platform of open source libraries and robust services to make
Description looks cut off.

2020-03-19 21:46 UTC, space-pope reviewed
Had some minor copy suggestions

2020-03-19 21:46 UTC, space-pope commented on content/blog/keeping-perspective.md
> +Nine years ago, before we knew the full impact of how mobile and social services might affect our lives, Wilson referenced a quote that not only addressed these (at the time) nascent products but eve
```suggestion
Nine years ago, before we knew the full impact of how mobile and social services might affect our lives, Wilson referenced a quote that not only addressed these (at the time) nascent products but everyday products we already take for granted. The quote was from Marshall McLuhan:
```

2020-03-19 21:46 UTC, space-pope commented on content/blog/keeping-perspective.md
> +> We Shape Our Tools, and Thereafter Our Tools Shape Us
```suggestion
> We shape our tools, and thereafter our tools shape us.
```

2020-03-19 21:46 UTC, space-pope commented on content/blog/keeping-perspective.md
> +Whether a direct quote from McLuhan or an adaption from a [Churchill quote on rebuilding England’s House of Commons building](https://quoteinvestigator.com/2016/06/26/shape/), this adage is a reminde
```suggestion
Whether a direct quote from McLuhan or an adaptation from a [Churchill quote on rebuilding England’s House of Commons building](https://quoteinvestigator.com/2016/06/26/shape/), this adage is a reminder that the things we build have an impact on the world. Even if it [looks like a toy at first](https://cdixon.org/2010/01/03/the-next-big-thing-will-start-out-looking-like-a-toy), like [Chris Dixon](https://twitter.com/cdixon) said 10 years ago. Sometimes at the beginning of a project, you may not fully understand all the potential uses for what you are building. But if you’re lucky and keep your eyes and ears open, some of those uses may find you.
```

2020-03-19 21:46 UTC, space-pope commented on content/blog/keeping-perspective.md
> +As we have spoken with different groups about how our service might help companies, one of the most common features is better accessibility for users who need more than a touchscreen to use their app
```suggestion
As we have spoken with different groups about how our service might help companies, one of the most commonly mentioned features is better accessibility for users who need more than a touchscreen to use their app. There are already a few companies that build hardware specifically for visually impaired users. There are also companies like [Tecla](https://gettecla.com/pages/tecla-e) that build devices to help those with limited upper-body mobility to use mobile devices. The more we’ve started to research this area, the more we've realized that we could enable better usability for the millions of people who could benefit from a voice interface for mobile apps.
```

2020-03-19 21:46 UTC, space-pope commented on content/blog/keeping-perspective.md
> +New companies are always looking for product-market fit for all the obvious business reasons. However, in times like these it can fill overwhelming trying to build a business and not know how it migh
```suggestion
New companies are always looking for product-market fit for all the obvious business reasons. However, in times like these it can feel overwhelming trying to build a business and not knowing how it might help the overwhelming needs of society.
```

2020-03-19 21:46 UTC, space-pope commented on content/blog/keeping-perspective.md
> +If you have any ideas or specific problems where our voice interface experience can improve you or your users’ lives, please reach out to us and help us shape Spokestack into a better tool.
```suggestion
If you have any ideas or specific problems where our voice interface experience can improve your or your users’ lives, please reach out to us and help us shape Spokestack into a better tool.
```
Should "reach out to us" be a link?

2020-03-20 19:29 UTC, timmywil commented
@miketatum did you mean to close this? Just making sure you know you can just keep updating the same PR.

2020-03-20 21:52 UTC, timmywil approved these changes

2020-03-20 21:52 UTC, merged

2020-03-20 22:20 UTC, timmywil commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack-website/releases/tag/1.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: