docs(ios): update Getting Started and Cookbook with NLU sections
spokestack/spokestack-website pull request #50
Opened 2020-03-30 20:38 UTC by noelweichbrodt

2020-03-30 21:11 UTC, space-pope reviewed
Just a few minor updates/formatting changes for your consideration. Thanks for getting this out there.

2020-03-30 21:11 UTC, space-pope commented on content/docs/iOS/cookbook.md
> +Sticking with a timer app example, here's how to extract a slot value from an `NLUResult`, like one delivered to `NLUDelegate`'s `cliassification` event. Note that the intent and slot names area pre-
```suggestion
Sticking with the timer app example, here's how to extract a slot value from an `NLUResult`, like one delivered to `NLUDelegate`'s `classification` event. Note that the intent and slot names are pre-determined by the NLU model metadata.
```

2020-03-30 21:11 UTC, space-pope commented on content/docs/iOS/cookbook.md
> +```
```suggestion
```swift
```

2020-03-30 21:11 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +Inside `SpeechEventListener`'s' `didRecognize` delegate function, the `result.transcript` will give you the raw text of what the user just said. Translating that raw text into an action in your app i
```suggestion
Inside `SpeechEventListener`'s' `didRecognize` delegate function, the `result.transcript` will give you the raw text of what the user just said. Translating that raw text into an action in your app is the job of an NLU, or natural language understanding, component. Spokestack leaves the choice of NLU up to you, but we do offer our own full-featured NLU component for Spokestack based on years of research and lessons learned from working with other services. Our NLU runs directly on your user's device, instead of calling back to the cloud. If you're a fan of the cloud, though, you might want to check out ([DialogFlow](https://dialogflow.com/), [LUIS](https://www.luis.ai/home), or [wit.ai](https://wit.ai/). And if your app is simple enough, you can make your own NLU with string matching or regular expressions (see the [cookbook](cookbook) for an example of this).
```

2020-03-30 21:11 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +```
```suggestion
```swift
```

2020-03-30 21:11 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +Earlier, if you recalled, we claimed that `MyViewController` already implemented the `NLUDelegate` protocol. The `nlu.classify` call above will return the classification results to a function in that
```suggestion
Earlier, if you recall, we claimed that `MyViewController` already implemented the `NLUDelegate` protocol. The `nlu.classify` call above will return the classification results to a function in that delegate.
```

2020-03-30 21:11 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +```
```suggestion
```swift
```

2020-03-30 21:11 UTC, space-pope commented on content/docs/iOS/cookbook.md
> +            let units = result.slots["duration"].type
In this example, the value of your `units` var would just be `integer`—you'd want a separate entity/selset slot to express the actual units.

2020-03-31 14:01 UTC, timmywil requested changes

2020-03-31 14:01 UTC, timmywil commented on .eslintignore
> +content/docs/
Docs should pass eslint. This should be removed.

2020-03-31 14:12 UTC, timmywil commented on .eslintignore
> +content/docs/
I just checked and your PR passes already without this line. Just need to remove it.

2020-03-31 14:12 UTC, noelweichbrodt commented on .eslintignore
> +content/docs/
```
✖ eslint found some errors. Please fix them and try committing again.

/Users/noel/w/spokestack-website/content/docs/iOS/cookbook.md
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: content/docs/iOS/cookbook.md.
The extension for the file (.md) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

/Users/noel/w/spokestack-website/content/docs/iOS/getting-started.md
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: content/docs/iOS/getting-started.md.
The extension for the file (.md) is non-standard. You should add "parserOptions.extraFileExtensions" to your config
```
and if you do add `[".md"]` to `parserOptions.extraFileExtensions`, eslint can't parse Markdown files:
```
✖ eslint found some errors. Please fix them and try committing again.

/Users/noel/w/spokestack-website/content/docs/iOS/cookbook.md
  1:2  error  Parsing error: Expression expected

/Users/noel/w/spokestack-website/content/docs/iOS/getting-started.md
  1:2  error  Parsing error: Expression expected
```

2020-03-31 14:18 UTC, timmywil commented on .eslintignore
> +content/docs/
Ah, I had this error too. `rm -rf node_modules/ && npm i`

2020-03-31 14:19 UTC, timmywil commented on .eslintignore
> +content/docs/
Maybe just `npm i` if you haven't done that yet.

2020-03-31 14:21 UTC, noelweichbrodt commented on .eslintignore
> +content/docs/
I had already done `npm i`, i'll try blowing everything away first.

2020-03-31 14:35 UTC, noelweichbrodt commented on .eslintignore
> +content/docs/
yep, that fixed it.

2020-03-31 15:26 UTC, timmywil commented on .eslintignore
> +content/docs/
@noelweichbrodt don't forget to push

2020-03-31 20:13 UTC, space-pope reviewed
LGTM, except for my own proofreading fail.

2020-03-31 20:13 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +Inside `SpeechEventListener`'s' `didRecognize` delegate function, the `result.transcript` will give you the raw text of what the user just said. Translating that raw text into an action in your app i
```suggestion
Inside `SpeechEventListener`'s' `didRecognize` delegate function, the `result.transcript` will give you the raw text of what the user just said. Translating that raw text into an action in your app is the job of an NLU, or natural language understanding, component. Spokestack leaves the choice of NLU up to you, but we do offer our own full-featured NLU component for Spokestack based on years of research and lessons learned from working with other services. Our NLU runs directly on your user's device, instead of calling back to the cloud. If you're a fan of the cloud, though, you might want to check out [DialogFlow](https://dialogflow.com/), [LUIS](https://www.luis.ai/home), or [wit.ai](https://wit.ai/). And if your app is simple enough, you can make your own NLU with string matching or regular expressions (see the [cookbook](cookbook) for an example of this).
```
...sorry; this one was my fault. Missed deleting that leading paren the first time around and only caught it on a re-read.

2020-03-31 20:29 UTC, space-pope approved these changes

2020-03-31 20:46 UTC, timmywil approved these changes

2020-03-31 20:47 UTC, timmywil commented
I approve, but format probably needs to run on the stuff directly committed from github.

2020-03-31 21:00 UTC, merged

2020-04-29 19:50 UTC, timmywil commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack-website/releases/tag/1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: