docs: android NLU explanation
spokestack/spokestack-website pull request #51
Opened 2020-04-02 21:54 UTC by space-pope

Since iOS got ahead of me here, I went ahead and updated the Android guides to include new NLU features and added a new one to explain the design a bit. Some of it is Android-specific, but most of the concepts are universal; I'm open to ideas about making the new guide something for the top-level concepts section and having platform-specific breakouts.

2020-04-03 20:50 UTC, noelweichbrodt requested changes
Thanks for documenting the NLU system! I'd like some reorganization around the new NLU doc since the majority of it is a conceptual guide that applies to both android and ios. I made suggestions on how to move the platform-specific parts of it into other appropriate platform places, but feel free to move them where you think best.

2020-04-03 20:50 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +title: NLU on Android
I think this doc should be split up into a new `concepts/nlu.md` doc, and the `Usage` section transferred into `Android/getting-started.md`.

2020-04-03 20:50 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +title: NLU on Android
You could further split `Usage` by putting `### 2) Callback` into the cookbook.

2020-04-03 20:50 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +title: NLU on Android
Everything outside `Usage` is applicable to iOS too, so it shouldn't be siloed as Android-only.

2020-04-03 20:50 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +An entity slot represents a value with a specific meaning in the current domain. No transformation is performed on this type; its value is a `String` extracted directly from the ASR result.
```suggestion
An entity slot represents a value with a specific meaning in the current domain. No transformation is performed on this type; its value is a `String` extracted directly from the input utterance.
```

2020-04-03 20:50 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +An integer slot, as implied by the name, attempts to parse a spoken numeric value into an `int` value. Spoken values may be ordinal or cardinal ("third" or "three", respectively), and the integer slo
```suggestion
An integer slot, as implied by the name, attempts to parse a numeric value into an `int` value. Numeric values may be ordinal or cardinal ("third" or "three", respectively), and the integer slot interprets powers of 10 in the opposite way that the digits slot does: "eight hundred fifty-six" will be rendered as `856`.
```

2020-04-03 20:50 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +Values up to Java's `Integer.MAX_VALUE` are supported, but model metadata specifies the acceptable range of values for the particular slot; values outside that range result in an error.
This note is probably more appropriate for code documentation, not a docs guide.

2020-04-03 20:50 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +## Usage
This document should be broken up at this point, with the `Usage` section and  `### 1) Blocking call` moving to `Android/getting-started.md`.

2020-04-03 20:50 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +### 2) Callback
This section should be moved to the Android cookbook (since it covers an alternative to what would be in Getting Started).

2020-04-03 20:50 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +## Interpreting the results
This and the following sections should be combined with the earlier `The basics` section into a new document at `Concepts/nlu.md`

2020-04-03 21:06 UTC, space-pope commented on content/docs/Android/nlu.md
> +title: NLU on Android
That's mostly correct, but the types are going to be different in Swift.

2020-04-03 21:08 UTC, space-pope commented on content/docs/Android/nlu.md
> +Values up to Java's `Integer.MAX_VALUE` are supported, but model metadata specifies the acceptable range of values for the particular slot; values outside that range result in an error.
Another reason this is in the Android section 😛

2020-04-03 21:09 UTC, space-pope commented on content/docs/Android/nlu.md
> +## Usage
The getting started guide already has this snippet; the division is important enough to explain at length and not bury in a recipe.

2020-04-03 21:13 UTC, space-pope commented
I'll chew on this a bit. I had already considered the main thing you've suggested—a platform-agnostic `concepts` guide—but I think the platform-specific usage stuff also deserves a proper treatment, and outside the quickstart guides, which should be as brief as possible.

I think the best middle ground might be to follow most of the breakdown you've suggested, but _also_ have nlu guides under `ios` and `android` that explain decisions around background processing/dispatch queues and whanot.

2020-04-03 21:17 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +title: NLU on Android
Wow, github lost this comment thread in my review, and I rewrote it in different places below :( sorry for the duplication.

2020-04-03 21:18 UTC, noelweichbrodt commented on content/docs/Android/nlu.md
> +Values up to Java's `Integer.MAX_VALUE` are supported, but model metadata specifies the acceptable range of values for the particular slot; values outside that range result in an error.
It's an island of platform specificity in a sea of platform-independent concepts.

2020-04-03 21:19 UTC, noelweichbrodt commented
I'd be fine with platform-specific `nlu.md` in addition to my suggestion for `Concepts/nlu.md`. The alternative is a stupid copypasta of this stuff into ios.

2020-04-06 20:09 UTC, space-pope commented
See what you think of this, @noelweichbrodt . Feel free to add an iOS page into this PR (I've already created a link to such a hypothetical page, but I can remove it) or see if there's anything else you'd like to see. There's admittedly some more info that could be included here, but I'm in "explain things to a reasonable degree" mode right now.

2020-04-06 21:49 UTC, noelweichbrodt approved these changes
LGTM, thanks for breaking it up. I'll add an `ios/nlu.md` here in a bit.

2020-04-07 20:18 UTC, space-pope commented on content/docs/iOS/nlu.md
> +This is a companion to the [NLU concept guide](docs/Concepts/nlu), which discusses the NLU subsystem holistically. Here we'll talk about usage issues specific to the Android client library.
Mmm, pasta.
```suggestion
This is a companion to the [NLU concept guide](docs/Concepts/nlu), which discusses the NLU subsystem holistically. Here we'll talk about usage issues specific to the iOS client library.
```

2020-04-07 20:18 UTC, space-pope commented on content/docs/iOS/nlu.md
> +The following properties are configurable, but should not be changed unless a different NLU model or vocabulary is being used (ie if you're changing this, you already know why you're doing so):
```suggestion
The following properties are configurable, but should not be changed unless a different NLU model or vocabulary is being used (i.e., if you're changing these, you already know why you're doing so):
```

2020-04-07 20:18 UTC, space-pope commented on content/docs/iOS/nlu.md
> +- `nluPaddingTokenIndex`
```suggestion
```

2020-04-07 20:18 UTC, space-pope commented on content/docs/iOS/nlu.md
> +assuming that `self` implements `NLUDelegate`.
There's nothing to assume; you do it explicitly here.

2020-04-07 20:18 UTC, space-pope commented on content/docs/iOS/nlu.md
> +As mentioned in the [Getting Started](getting-started) guide, initializing the Spokestack NLU is like inititalizing the TTS component. Both a delegate callback interface and a publisher interface are
```suggestion
As mentioned in the [Getting Started](getting-started) guide, initializing the Spokestack NLU is like initializing the TTS component. Both a delegate callback interface and a publisher interface are provided. The call to `classify` is the same for either interface, but the result and `DispatchQueue` that the classification runs on are handled differently.
```

2020-04-08 14:21 UTC, merged

2020-04-29 19:50 UTC, timmywil commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack-website/releases/tag/1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: