docs(ios): speech delegate clarifications
spokestack/spokestack-website pull request #61
Opened 2020-04-29 20:44 UTC by pdtyreus

Updated description of when `SpeechDelegate` methods are called and what needs to happen for various use cases.

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [x] I have run `npm test` against my changes and tests pass.
- [x] I have added or edited necessary documentation, or no docs changes are needed.

### Description

Updates on iOS documentation based on Studio app development findings.

2020-04-29 21:09 UTC, space-pope reviewed
Just a couple proofing edits below. Hopefully we'll be able to half-revert some of these `SpeechDelegate` caveats before too long, but it's good to have the current state of things laid out.

2020-04-29 21:09 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +If a wakeword-driven experience isn't for you, or if you want to give users a tap-to-talk option, just call `pipeline.start()` followed by `pipeline.activate()` in the action of whatever button you w
```suggestion
If a wakeword-driven experience isn't for you, or if you want to give users a tap-to-talk option, just call `pipeline.start()` followed by `pipeline.activate()` in the action of whatever button you want to activate the microphone. This skips the wakeword step of the pipeline and starts the automatic speech recognition (ASR) component directly. ASR will stop automatically after the user is silent for a few seconds (how _many_ seconds is one of the configuration parameters we hinted at earlier) or after a preconfigured timeout is reached, but if you need to stop listening immediately for any reason, just call `pipeline.deactivate()`. You can then call `pipeline.activate()` to start ASR again or `pipeline.stop()` to shut the pipeline down completely.
```

2020-04-29 21:09 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +- `SpeechDelegate.deactivate`: called after ASR has been completed or timed out. Note that this is not called after a manual `pipeline.deactivate()`.
```suggestion
- `SpeechDelegate.deactivate`: called after ASR has completed or timed out. Note that this is not called after a manual `pipeline.deactivate()`.
```

2020-04-29 21:09 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +If you start the pipeline from a user interaction like a button press that calls `pipeline.activate()`, `SpeechDelegate.activate` will not be called. If you wish to display a "listening" indicator in
```suggestion
If you start the pipeline from a user interaction like a button press that calls `pipeline.activate()`, `SpeechDelegate.activate` will not be called. If you wish to display a "listening" indicator in your UI, you should do so in the same method that calls `pipeline.activate()` but remove it when `SpeechDelegate.deactivate` is called.
```

2020-04-29 21:12 UTC, noelweichbrodt reviewed
Good changes, thanks! Caught one typo.

2020-04-29 21:12 UTC, noelweichbrodt commented on content/docs/iOS/getting-started.md
> +If a wakeword-driven experience isn't for you, or if you want to give users a tap-to-talk option, just call `pipeline.start()` followed by `pipeline.activate()` in the action of whatever button you w
```suggestion
If a wakeword-driven experience isn't for you, or if you want to give users a tap-to-talk option, just call `pipeline.start()` followed by `pipeline.activate()` in the action of whatever button you want to activate the microphone. This skips the wakeword step of the pipeline and starts the automatic speech recognition (ASR) component directly. ASR will stop automatically after the user is silent for a few seconds (how _many_ seconds is one of the configuration parameters we hinted at earlier) or after a preconfigured timeout is reached, but if you need to stop listening immediately for any reason, just call `pipeline.deactivate()`. You can also call `pipeline.activate()` to start ASR again or `pipeline.stop()` to shut the pipeline down completely.
```

2020-04-29 21:13 UTC, noelweichbrodt commented
lol josh and I, of course, chose differing parts of that sentence fragment 😭

2020-04-30 15:52 UTC, timmywil requested changes
Minor change requested. I don't like saying "just" or "simply" in documentation.

2020-04-30 15:52 UTC, timmywil commented on content/docs/iOS/getting-started.md
> +If a wakeword-driven experience isn't for you, or if you want to give users a tap-to-talk option, just call `pipeline.start()` followed by `pipeline.activate()` in the action of whatever button you w
```suggestion
If a wakeword-driven experience isn't for you, or if you want to give users a tap-to-talk option, call `pipeline.start()` followed by `pipeline.activate()` in the action of whatever button you want to activate the microphone. This skips the wakeword step of the pipeline and starts the automatic speech recognition (ASR) component directly. ASR will stop automatically after the user is silent for a few seconds (how _many_ seconds is one of the configuration parameters we hinted at earlier) or after a preconfigured timeout is reached, but if you need to stop listening immediately for any reason, call `pipeline.deactivate()`. You can then call `pipeline.activate()` to start ASR again or `pipeline.stop()` to shut the pipeline down completely.
```

2020-04-30 19:31 UTC, timmywil approved these changes

2020-05-07 18:43 UTC, merged

2020-05-12 18:05 UTC, timmywil commented
:tada: This PR is included in version 1.10.0 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack.io/releases/tag/1.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: