docs(blog): export to independence blog articles 1-5
spokestack/spokestack-website pull request #72
Opened 2020-06-08 22:15 UTC by pdtyreus

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [x] I have run `npm test` against my changes and tests pass.
- [x] I have added or edited necessary documentation, or no docs changes are needed.

### Description

First 5 articles in the "Porting a Smart Speaker Voice App to Mobile" series including first 2 tutorials.

**Fixes**: #

2020-06-09 19:08 UTC, timmywil requested changes
Some nits

2020-06-09 19:08 UTC, timmywil commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +The easiest way to install Spokestack on iOS is using CocoaPods as described in more detail in the [getting started docs](https://spokestack.io/docs/iOS/getting-started). Download and unzip the [exam
```suggestion
The easiest way to install Spokestack on iOS is using CocoaPods as described in more detail in the [getting started docs](/docs/iOS/getting-started). Download and unzip the [example code](https://d3dmqd7cy685il.cloudfront.net/docs/minecraft-ios-tutorial.zip). In the "start" folder, you’ll see a `Podfile` with the following contents:
```

2020-06-09 19:08 UTC, timmywil commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +The example code contains a class `PipelineStore` that implements [the delegates](https://spokestack.io/docs/iOS/speech-pipeline) in the Spokestack speech pipeline. The `init` method of our `ContentV
```suggestion
The example code contains a class `PipelineStore` that implements [the delegates](/docs/iOS/speech-pipeline) in the Spokestack speech pipeline. The `init` method of our `ContentView` already calls the `pipelineStore.start()` method to start background processing. To begin actually listening, add a new function to `PipelineStore`:
```

2020-06-09 19:08 UTC, timmywil commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +![](screen2.gif)
Could use an alt.

2020-06-09 19:08 UTC, timmywil commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +![](screen1.png)
Could use an alt for the image.

2020-06-09 19:08 UTC, timmywil commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +![](screen3.gif)
alt

2020-06-09 20:18 UTC, pdtyreus commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +The easiest way to install Spokestack on iOS is using CocoaPods as described in more detail in the [getting started docs](https://spokestack.io/docs/iOS/getting-started). Download and unzip the [exam
fixed

2020-06-09 20:19 UTC, pdtyreus commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +The example code contains a class `PipelineStore` that implements [the delegates](https://spokestack.io/docs/iOS/speech-pipeline) in the Spokestack speech pipeline. The `init` method of our `ContentV
fixed

2020-06-09 20:19 UTC, pdtyreus commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +![](screen2.gif)
added alt

2020-06-09 20:19 UTC, pdtyreus commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +![](screen1.png)
added alt

2020-06-09 20:19 UTC, pdtyreus commented on content/blog/porting-the-alexa-minecraft-skill-to-ios-using-spokestack/index.md
> +![](screen3.gif)
added alt

2020-06-09 21:47 UTC, timmywil approved these changes

2020-06-09 21:47 UTC, merged

2020-06-10 16:55 UTC, timmywil commented
:tada: This PR is included in version 1.17.0 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack.io/releases/tag/1.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: