docs: wakeword blog post
spokestack/spokestack-website pull request #77
Opened 2020-06-11 19:21 UTC by noelweichbrodt

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [ ] I have run `npm test` against my changes and tests pass.
- [ ] I have added or edited necessary documentation, or no docs changes are needed.

### Description

**Fixes**: #

2020-06-11 19:37 UTC, space-pope reviewed
Just a couple mostly optional suggestions. Good stuff!

2020-06-11 19:37 UTC, space-pope commented on content/blog/which-wakeword-would-we-want/index.md
> +Indeed! If you want your app to be controllable purely by voice, you need a wakeword — a word (or short phrase) that tells your app “the next thing the user says is meant for you”. The wakeword detec
```suggestion
Indeed! If you want your app to be controllable purely by voice, you need a wakeword — a word (or short phrase) that tells your app “the next thing the user says is meant for you”. The wakeword detection component in Spokestack is responsible for detecting any of a user-defined set of keyword phrases in [soft real time](https://en.wikipedia.org/wiki/Real-time_computing#Criteria_for_real-time_computing). Once detected, the Spokestack pipeline activates, providing you with an activation event and triggering the configured speech recognition service. The accuracy, speed, and flexibility of wakeword detection depends on which service you configure.
```

2020-06-11 19:37 UTC, space-pope commented on content/blog/which-wakeword-would-we-want/index.md
> +Spokestack's `tfLiteWakeword` fits the bill for you! You'll gain fast, accurate, efficient, wakeword activation that runs entirely on-device. It features a state of the art machine learning pipeline
```suggestion
Spokestack's `tfLiteWakeword` fits the bill for you! You'll gain fast, accurate, efficient, wakeword activation that runs entirely on-device. It features a state-of-the-art machine learning pipeline using attention-based models; they operate continuously, each feeding output into the next, for both efficiency and accuracy.
```
Phrases like this should typically be hyphenated when used as an adjective and unhyphenated when used as a noun.

2020-06-12 15:52 UTC, timmywil requested changes

2020-06-12 15:52 UTC, timmywil commented on content/blog/which-wakeword-would-we-want/index.md
> +# Spokestack offers two wakeword services in iOS: `appleWakeword` and `tfLiteWakeword`. Which should you use?
The main header is automatically added based on the title in the frontmatter. Here's my suggestion...

```suggestion
---
title: Choosing the Right Wakeword Service in iOS
date: '2020-06-12'
description: Spokestack offers two wakeword services in iOS: `appleWakeword` and `tfLiteWakeword`. Which should you use?
author: noel
tags: Engineering
draft: false
---

Spokestack offers two wakeword services in iOS: `appleWakeword` and `tfLiteWakeword`. Which should you use?
```

2020-06-12 16:07 UTC, timmywil commented on content/blog/which-wakeword-would-we-want/index.md
> +# Spokestack offers two wakeword services in iOS: `appleWakeword` and `tfLiteWakeword`. Which should you use?
I'd also change the filename to match the title (all lowercase and spaces replace with `-`)

2020-06-16 14:39 UTC, timmywil approved these changes

2020-06-16 14:39 UTC, merged

2020-06-16 15:30 UTC, timmywil commented
:tada: This PR is included in version 1.19.3 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack.io/releases/tag/1.19.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: