docs(blog): independence day
spokestack/spokestack-website pull request #83
Opened 2020-06-15 21:59 UTC by noelweichbrodt

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [ ] I have run `npm test` against my changes and tests pass.
- [ ] I have added or edited necessary documentation, or no docs changes are needed.

### Description

New blog post: Independence Day

**Fixes**: #

2020-06-16 01:43 UTC, space-pope reviewed
👍

2020-06-16 01:43 UTC, space-pope commented on content/blog/independence-day/independence-day.md
> +NLU-capable computers everywhere -- your smart phone, your smart watch, your laptop, your tv -- but nobody is building NLU-enabled apps for them. Smart speakers, on the other hand, are essentially NL
```suggestion
NLU-capable computers are everywhere -- your smartphone, your smartwatch, your laptop, your TV — but nobody is building NLU-enabled apps for them. Smart speakers, on the other hand, are essentially NLU-only voice app platforms. Why do you have to choose between them? With Spokestack, you don't. [Export your smart speaker skill](https://spokestack.io/docs/Concepts/export) to run on the major mobile platforms and declare your independence!
```

2020-06-16 01:43 UTC, space-pope commented on content/blog/independence-day/independence-day.md
> +![Today we celebrate our Independence Day!](https://zippy.gfycat.com/UnkemptInsignificantGelding.webm)
Don't think the webm is being processed as an image.

2020-06-16 01:43 UTC, space-pope commented on content/blog/independence-day/independence-day.md
> +![Will Smith walks away from smoke](https://gph.is/28Qnphp)
Same here; image link looks broken in preview.

2020-06-16 01:43 UTC, space-pope commented on content/blog/independence-day/independence-day.md
> +What do you gain from that? You control and learn from the NLU classification of user utterances, not the smart speaker platform. When you're stuck on a smart speaker, do you get the raw utterance th
```suggestion
What do you gain from that? You control and learn from the NLU classification of user utterances, not the smart speaker platform. When you're stuck on a smart speaker, do you get the raw utterance that your user uses when they're in your skill, even misclassified or misunderstood ones? With Spokestack, you control your data and your users' data.
```
You do get the raw utterance with Dialogflow...just not with Alexa unless you do something clever.

2020-06-16 01:43 UTC, space-pope commented on content/blog/independence-day/independence-day.md
> +You can leverage existing ASR and TTS services, which are the parts that actually benefit from scale and are difficult to DIY. Spokestack provides [a seamless, unified API]() across mobile platforms
```suggestion
You can leverage existing ASR and TTS services, which are the parts that actually benefit from scale and are difficult to DIY. Spokestack provides a seamless, unified API across mobile platforms ([iOS](https://spokestack.io/docs/iOS), [Android](https://spokestack.io/docs/Android), and [React/React Native](https://spokestack.io/docs/React%20Native)) that makes integrating your skill into an app easy.
```

2020-06-16 01:43 UTC, space-pope commented on content/blog/independence-day/independence-day.md
> +description: With Spokestack, your smart speaker skill can declare independence!
```suggestion
description: With Spokestack, your voice app can declare independence!
```
I think I'm with Daniel on standardizing around "voice app" (here and elsewhere in the post)—only Alexa apps are "skills", as Google so pedantically reminded me recently.

2020-06-16 14:42 UTC, timmywil commented
Minor nit: I'd prefer relative URLs where possible.

2020-06-18 22:49 UTC, timmywil requested changes
Just need to fix images.

2020-06-22 18:46 UTC, timmywil approved these changes
I went ahead and fixed the images for you. Also, I think I was unclear before. When naming with a folder, the blog post filename should just be `index.md`, and the folder name will match the post title. When not using a folder, the filename would match the post title.

2020-06-22 22:34 UTC, timmywil commented
@noelweichbrodt Would you like this out? What date should we set?

2020-06-26 19:05 UTC, merged

2020-06-29 22:48 UTC, timmywil commented
:tada: This PR is included in version 1.19.8 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack.io/releases/tag/1.19.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: