docs: update iOS docs with new speech pipeline content
spokestack/spokestack-website pull request #87
Opened 2020-07-16 00:25 UTC by noelweichbrodt

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [x] I have run `npm test` against my changes and tests pass.
- [x] I have added or edited necessary documentation, or no docs changes are needed.

### Description

Update site docs for new iOS speech pipeline content

2020-07-20 15:48 UTC, space-pope requested changes
Request changes is just for the link/image updates; the rest is a mix of typo fixes and suggestions. Good stuff; nice to have this lining up so well.

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +There are many options for configuring the speech pipeline. This particular setup will begin capturing audio when `pipeline.start()` is called and use a Voice Activity Detection (VAD) component to se
`<nitpick>`The last sentence could probably stand to be broken up. `</nitpick>`

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +If you want your app to be controllable purely by voice, you need a wakeword -- a word (or short phrase) that tells your app "the next thing the user says is meant for you". Spokestack comes with a d
```suggestion
If you want your app to be controllable purely by voice, you need a wakeword — a word (or short phrase) that tells your app "the next thing the user says is meant for you". Spokestack comes with a default wakeword ("Spokestack", believe it or not), and that's enabled just by changing the pipeline profile enum in the `SpeechPipeline` we just set up. Try changing `.vadTriggerAppleSpeech` to `.appleWakewordAppleSpeech` in that first code example. Then, to begin listening for it, just call `pipeline.start()`.
```
This looks familiar—if you got it from the android version, it could stand to be changed there too. The double hyphens are an emacs convenience that I try to go back and fix before publishing, but sometimes I miss them.

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +![](images/speech_pipeline_android.png 'Android speech pipeline')
```suggestion
![](images/speech_pipeline_android.png 'iOS speech pipeline')
```
Might go ahead and rename the image while you're at it :). You'll need to put it in the `iOS/images` directory too—and you can get rid of the existing image while you're there.

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +As you can see, once the pipeline has been is built (after the return of `SpeechPipeline.Builder.build()`), calling `start()` puts it into a passive listening state—or it will if the pipeline has bee
```suggestion
As you can see, once the pipeline has been built (after the return of `SpeechPipelineBuilder.build()`), calling `start()` puts it into a passive listening state—or it will if the pipeline has been properly configured. You _could_ have an ASR class as the only stage, in which case an ASR request would start immediately upon calling `start()`. This is almost certainly not what you want.
```
D'oh. Plz to fix in android version too if you don't mind.

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +While the pipeline is listening passively, it sends audio through its stages a frame at a time (a "frame" defaults to 20 ms of audio, but [it's configurable](/docs/Concepts/pipeline-configuration)).
```suggestion
While the pipeline is listening passively, it sends audio through its stages a frame at a time (a "frame" defaults to 20 ms of audio, but [it's configurable](/docs/Concepts/pipeline-configuration)). That audio is not leaving the device, though; it's waiting for a stage to recognize a trigger word or phrase and set the pipeline's `SpeechContext` to `active`. The classes that do this in Spokestack typically have names that end in `Trigger`; see `WakewordTrigger` and `VADTrigger` for examples.
```
Since iOS has multiple wakeword components, `WakewordTrigger` (and probably the explanatory bit about the classes ending in `Trigger`) doesn't work here.

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +The wakeword service is in charge of, you guessed it, recognizing that the user has said your app's wakeword. On iOS, this defaults to using Apple's built-in ASR to detect your chosen wakeword, but f
```suggestion
The wakeword service is in charge of, you guessed it, recognizing that the user has said your app's wakeword. On iOS, this defaults to using Apple's built-in ASR to detect your chosen wakeword, but for better performance you might want to experiment with a customized TensorFlow Lite model. Spokestack comes with a set of models trained to detect "Spokestack" as a wakeword, but you're also free to train your own and configure Spokestack to use them at runtime. You can find descriptions of the models' requirements in our [wakeword models guide](/docs/Concepts/wakeword-models), but if building and training them isn't something you want to take on, [send us an email](mailto:hello@spokestack.io), and we can discuss customization options.
```

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +The wakeword service is in charge of, you guessed it, recognizing that the user has said your app's wakeword. On iOS, this defaults to using Apple's built-in ASR to detect your chosen wakeword, but f
The transition from describing individual profiles to this overview seemed a little rough to me. It could maybe use a sentence about how profile names are structured (wakeword, then asr service) to introduce this section.

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +Profiles take care of all configuration that can be managed in a one-size-fits-all fashion, but note that some components require additional configuration, such as third-party API keys, paths to Tens
`For example, note the paths to the wakeword models in the example above.`

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +Your implementations of all these methods will be very important to how your app handles voice interactions, because the delegate acts as a kind of gatekeeper between speech events and pipeline opera
This paragraph will be a good place to put a plug for the Tray component.

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +Your implementations of all these methods will be very important to how your app handles voice interactions, because the delegate acts as a kind of gatekeeper between speech events and pipeline opera
```suggestion
Your implementations of all these methods will be very important to how your app handles voice interactions, because the delegate acts as a kind of gatekeeper between speech events and pipeline operation. You'll recall that earlier we mentioned a UI "listening" indicator would go in `speechDelegate`'s `didActivate` method, and that's true in many cases — often you'll want to alert the user that you're expecting a voice command from them (that the ASR component is active and interpreting their speech). If, however, you want to let the user know that the device's microphone _itself_ is active (which it naturally will be when waiting for a wakeword), you'll want to condition that indicator on the pipeline's `start` and `stop` events. The types of events it receives depend on whether the ASR has been activated from a wakeword or by using `pipeline.activate()`.
```
I'd also review references to method calls and standardize on either `classname.method` or `instance.method()`.

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
>  If you start the pipeline from a user interaction like a button press that calls `pipeline.activate()`, `SpeechDelegate.activate` will not be called. If you wish to display a "listening" indicator in
```suggestion
If you start the pipeline from a user interaction like a button press that calls `pipeline.activate()`, `SpeechDelegate.didActivate` will not be called. If you wish to display a "listening" indicator in your UI, you should do so in the same method that calls `pipeline.activate()` but remove it when `SpeechDelegate.didDeactivate` is called.
```

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +- `tracing`: If you want more verbose debug logging from Spokestack components, setting this to `.TRACE` or `.DEBUG` will make you satisfied.
```suggestion
- `tracing`: If you want more verbose debug logging from Spokestack components, set this to `.TRACE` or `.DEBUG`.
```

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +- (`filter`|`detect`|`encode`)`ModelName`: Names for custom [TensorFlow Lite](https://www.tensorflow.org/lite) wakeword models. Training custom models is outside the scope of this guide, but you can
```suggestion
- (`filter`|`detect`|`encode`)`ModelName`: Names for custom [TensorFlow Lite](https://www.tensorflow.org/lite) wakeword models. Training custom models is outside the scope of this guide, but you can find a description of their requirements in our [wakeword models guid](/docs/Concepts/wakeword-models).
```

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +The pipeline can also be activated by calling its `activate` method. This is what you'd do to implement push-to-talk. Once activated, it can be deactivated by calling `deactivate`, or it will remain
According to a little later on, this is `wakeActiveMin`/`wakeActiveMax` in iOS.

2020-07-20 15:48 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +Once created, a single instance of `SpeechPipeline` can be stopped and restarted at will; just remember that Spokestack cannot use the device's microphone when it is stopped, and that stopping and st
```suggestion
Once created, a single instance of `SpeechPipeline` can be stopped and restarted at will; just remember that Spokestack cannot use the device's microphone when it is stopped, and that `start` and `stop` are much more expensive than `activate`/`deactivate`.
```

2020-07-20 17:24 UTC, noelweichbrodt commented on content/docs/iOS/getting-started.md
> +There are many options for configuring the speech pipeline. This particular setup will begin capturing audio when `pipeline.start()` is called and use a Voice Activity Detection (VAD) component to se
I love Josh-incepting the docs :)

2020-07-20 17:25 UTC, noelweichbrodt commented on content/docs/iOS/getting-started.md
> +If you want your app to be controllable purely by voice, you need a wakeword -- a word (or short phrase) that tells your app "the next thing the user says is meant for you". Spokestack comes with a d
yep, almost all the getting-started changes are copied from android

2020-07-20 17:42 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +There are many options for configuring the speech pipeline. This particular setup will begin capturing audio when `pipeline.start()` is called and use a Voice Activity Detection (VAD) component to se
I am my own harshest critic...after having sufficient time away from my work.

2020-07-20 20:25 UTC, space-pope reviewed
Nice; thanks for the updates. Just saw one missing preposition (and one retraction; my bad).

2020-07-20 20:25 UTC, space-pope commented on content/docs/Android/getting-started.md
> +There are many options for configuring the speech pipeline. This particular setup will begin capturing audio when `pipeline.start()` is called and use a Voice Activity Detection (VAD) component to se
```suggestion
There are many options for configuring the speech pipeline. This particular setup will begin capturing audio when `pipeline.start()` is called and use a Voice Activity Detection (VAD) component to send any audio determined to be speech through on-device ASR using Android's `SpeechRecognizer` API. In other words, the app is always actively listening, and no wakeword detection is performed. See [the configuration guide](/docs/Android/speech-pipeline) for more information about pipeline building options. Using a `VADTrigger*` profile is a good way to test out ASR without having to tap a button to activate it or downloading and configuring wakeword models. Consider your use-case fully before using it in production, however, since it will capture all speech it hears, not just what's directed at your app.
```

2020-07-20 20:25 UTC, space-pope commented on content/docs/iOS/getting-started.md
> +There are many options for configuring the speech pipeline. This particular setup will begin capturing audio when `pipeline.start()` is called and use a Voice Activity Detection (VAD) component to se
```suggestion
There are many options for configuring the speech pipeline. This particular setup will begin capturing audio when `pipeline.start()` is called and use a Voice Activity Detection (VAD) component to send any audio determined to be speech through on-device ASR using Apple's `SFSpeech` API. In other words, the app is always actively listening, and no wakeword detection is performed. See [the configuration guide](/docs/iOS/speech-pipeline) for more information about pipeline building options. Using a `vadTriggerAppleSpeech` profile is a good way to test out ASR without having to tap a button to activate it or downloading and configuring wakeword models. Consider your use-case fully before using it in production, however, since it will capture all speech it hears, not just what's directed at your app.
```

2020-07-20 20:25 UTC, space-pope commented on content/docs/iOS/speech-pipeline.md
> +The pipeline can also be activated by calling its `activate` method. This is what you'd do to implement push-to-talk. Once activated, it can be deactivated by calling `deactivate`, or it will remain
Sorry; this was my fault. You're linking to the concepts guide, which uses the android names and lists the iOS variants inline.
```suggestion
The pipeline can also be activated by calling its `activate` method. This is what you'd do to implement push-to-talk. Once activated, it can be deactivated by calling `deactivate`, or it will remain active until a pre-set timeout is triggered (see `active-min` and `active-max` in the [configuration documentation](/docs/Concepts/pipeline-configuration)).
```

2020-07-21 01:01 UTC, space-pope approved these changes
LGTM!

2020-07-21 15:23 UTC, merged

2020-07-23 16:38 UTC, timmywil commented
:tada: This PR is included in version 1.22.0 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack.io/releases/tag/1.22.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: