feat(blog): add react-native-spokestack-tray tutorial
spokestack/spokestack-website pull request #97
Opened 2020-08-31 20:20 UTC by timmywil

### PR Checklist

Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I am requesting to **pull a topic/feature/bugfix branch** (right side). In other words, not _master_.
- [x] I have run `npm test` against my changes and tests pass.
- [x] I have added or edited necessary documentation, or no docs changes are needed.

### Description

This adds a blog post tutorial for how to install `react-native-spokestack-tray` and how to respond to user intents.

2020-08-31 21:26 UTC, space-pope requested changes
Good stuff. Just saw a couple missing words and had some other suggestions/comments.

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +[react-native-spokestack-tray](https://github.com/spokestack/react-native-spokestack-tray) is a React Native component that is designed to work in any application, regardless of its layout or navigat
```suggestion
[react-native-spokestack-tray](https://github.com/spokestack/react-native-spokestack-tray) is a React Native component that is designed to work in any application, regardless of its layout or navigation. It uses multiple existing React Native plugins, including [react-native-spokestack](https://github.com/spokestack/react-native-spokestack), to add voice experiences. With **on-device** wakeword, ASR, and NLU, the tray's `silent` mode works completely offline–TTS is the only service that requires a network.
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +With a few required props (and [lots of optional ones](https://github.com/spokestack/react-native-spokestack-tray#spokestacktray--component-props)), you can start building a customizable voice experi
`properties`? I know `props` is common in RN, though...

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +First, install the dependencies. Here's a one-linear to install `react-native-spokestack-tray` and its peer dependencies.
```suggestion
First, install the dependencies. Here's a one-liner to install `react-native-spokestack-tray` and its peer dependencies.
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +Our main dependency (react-native-spokestack) makes use of relatively new APIs only available in iOS 13+. Make sure to set your deployment target to iOS 13, and set the following
`set the following` where? That's a podfile thing, right?

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +We use [react-native-permissions](https://github.com/react-native-community/react-native-permissions) to check and request the Microphone permission (iOS and Android) and the Speech Recognition permi
```suggestion
We use [react-native-permissions](https://github.com/react-native-community/react-native-permissions) to check and request the Microphone permission (iOS and Android) and the Speech Recognition permission (iOS only). This library separates each permission into its own pod to avoid inflating your app with code you don't use. Add the following pods to your Podfile:
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +For the time-being, `use_frameworks!` does not work with Flipper, so we also need to disable Flipper. Remove any Flipper-related lines in your Podfile. In React Native 0.63.2, they look like this...
```suggestion
For the time being, `use_frameworks!` does not work with Flipper, so we also need to disable Flipper. Remove any Flipper-related lines in your Podfile. In React Native 0.63.2, they look like this:
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +Remove your existing Podfile.lock and Pods folder to ensure no conflicts, then install the pods...
```suggestion
Remove your existing Podfile.lock and Pods folder to ensure no conflicts, then install the pods:
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +Set the AudioSession category, to enable microphone input and play out of the speaker by default. This also enables input and playback over bluetooth.
```suggestion
Set the AudioSession category to enable microphone input and play from the speaker by default. This also enables input and playback over bluetooth.
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +While Flipper works on fixing their pod for `use_frameworks!`, we must disable Flipper in the meantime. We already removed the Flipper dependencies from Pods above, but there remains some code in the
```suggestion
While Flipper works on fixing their pod for `use_frameworks!`, we must disable Flipper. We already removed the Flipper dependencies from Pods above, but there remains some code in the AppDelegate.m that imports Flipper. There are two ways to fix this.
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +    <!-- To wakeword and ASR -->
```suggestion
    <!-- For wakeword and ASR -->
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +### Edit AndroidManifest.xml
These permissions should be merged in automatically from spokestack-android's manifest, though it's worth testing in an RN project to make sure.

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +```java
Gradle files are technically Groovy, but our syntax highlighter doesn't seem to understand that one yet.

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +Add the following lines
```suggestion
Add the following lines:
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +The [react-native-spokestack-tray example app](https://github.com/spokestack/react-native-spokestack-tray/tree/develop/example) uses the "Spokestack" wakeword and sample Minecraft NLU models.
Maybe worth a link to the minecraft tutorial series here just to give that a bit of context?

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +These URLs point to the sample Minecraft NLU models files we have hosted on a CDN, which are downloaded automatically by `SpokestackTray` the first time the app launches (and only the first time). Th
The size has varied from our earliest models to the current ones, but it's dependent on the underlying neural architecture rather than domain and shouldn't vary from app to app.

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +A good example is searching with voice. If your app has just said, "What would you like to search for?" and the user says, "Bananas", you can be reasonably sure that the user means for the app to sea
Heh, that's assuming you have a dialogue manager that knows what your app said last and how to interpret responses to it :).

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +But if the user initiated the interaction and said, "Search for bananas", the NLU can parse that statement into an intent (e.g. "search") with variables (e.g. "bananas"). If you were only using ASR,
```suggestion
But if the user initiated the interaction and said, "Search for bananas", the NLU can parse that statement into an intent (e.g. "search") with variables (e.g. "bananas"). If you were only using ASR, you'd probably end up searching for the whole sentence, "search for bananas", rather than just "bananas", which may yield different results. For more information on NLU in Spokestack, please check out [our guide](/docs/Concepts/nlu). If you've already built an NLU model in Alexa, Dialogflow, or Jovo, check out [our guide on exporting existing NLU models from other platforms](/docs/Concepts/export).
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +2. Should the app update the UI? Note that not all intents will need to make UI changes.
The other ordered list used `1.` for both items, fwiw.

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +In the voice search example, if the user has just searched for "bananas", the answer to question #1 might be to say, "Here are your search results." The answer to question #2 would probably be to sho
```suggestion
In the voice search example, if the user has just searched for "bananas", the answer to question #1 might be to say, "Here are your search results." The answer to question #2 would probably be to show the search results. Remember that the NLU doesn't do the search for you; it just tells you the proper search terms.
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +The `prompt` will then be synthesized using Spokestack's TTS service. It then gets played using the device's native audio player.
Unless the tray is in silent mode, right? Think that'd be a good thing to mention here, or maybe just save it for the more detailed component documentation?

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +If the node is specified in the [`exitNodes`](https://github.com/spokestack/react-native-spokestack-tray#optional-exitnodes) prop, the conversation will stop and `SpokestackTray` will close.
The dialogue manager will eventually make this less messy 🤞 .

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +If the `node` is not an exit node, `SpokestackTray` will stay open and will listen to the user again, and the process repeats.
```suggestion
If the `node` is not an exit node, `SpokestackTray` will stay open and listen to the user again, and the process will repeat.
```

2020-08-31 21:26 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +Hopefully, we've given you glimpse into just how powerful `react-native-spokestack-tray` can be. Add the `SpokestackTray` component to your React Native app to start building elegant conversational u
```suggestion
Hopefully, we've given you a glimpse into just how powerful `react-native-spokestack-tray` can be. Add the `SpokestackTray` component to your React Native app to start building elegant conversational user experiences.
```

2020-08-31 21:26 UTC, space-pope commented on gatsby-config.js
> +          email: ''
Heh, oops. we could probably include his email, though, or ask him what he wants here.

2020-08-31 21:26 UTC, space-pope commented on package.json
> -    "printWidth": 80,
I wholeheartedly support this for the docs section :).

2020-09-01 14:10 UTC, timmywil commented on content/blog/integrating-spokestack-in-react-native/index.md
> +With a few required props (and [lots of optional ones](https://github.com/spokestack/react-native-spokestack-tray#spokestacktray--component-props)), you can start building a customizable voice experi
I was back and forth on that, but I think `props` is the RN lingo.

2020-09-01 14:11 UTC, timmywil commented on content/blog/integrating-spokestack-in-react-native/index.md
> +Our main dependency (react-native-spokestack) makes use of relatively new APIs only available in iOS 13+. Make sure to set your deployment target to iOS 13, and set the following
This is in the "Edit Podfile" section, but I can be more specific. It goes at the top.

2020-09-01 14:14 UTC, timmywil commented on package.json
> -    "printWidth": 80,
I just removed it because it's the default. Also, `prettier` does not enforce this in markdown text by default, but we could do that.

2020-09-01 14:16 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +Our main dependency (react-native-spokestack) makes use of relatively new APIs only available in iOS 13+. Make sure to set your deployment target to iOS 13, and set the following
Oh right; totally forgot to look back at the heading because it looked like the sentence was incomplete.

2020-09-01 14:17 UTC, space-pope commented on package.json
> -    "printWidth": 80,
The column looks pretty narrow to me in the docs already, so I wouldn't add any new character limits; guess it's enforced elsewhere.

2020-09-01 14:31 UTC, timmywil commented on content/blog/integrating-spokestack-in-react-native/index.md
> +### Edit AndroidManifest.xml
I think it's good to specify top-level as well.

2020-09-01 14:35 UTC, timmywil commented on content/blog/integrating-spokestack-in-react-native/index.md
> +These URLs point to the sample Minecraft NLU models files we have hosted on a CDN, which are downloaded automatically by `SpokestackTray` the first time the app launches (and only the first time). Th
Seems like at least the list of utterances and metadata files at least would vary greatly from app to app.

2020-09-01 14:37 UTC, timmywil commented on gatsby-config.js
> +          email: ''
I've been getting details for authors, but I don't think will is an author yet.

2020-09-01 14:37 UTC, timmywil commented on package.json
> -    "printWidth": 80,
The column itself is just CSS. This is for code formatting.

2020-09-01 14:46 UTC, space-pope commented on content/blog/integrating-spokestack-in-react-native/index.md
> +These URLs point to the sample Minecraft NLU models files we have hosted on a CDN, which are downloaded automatically by `SpokestackTray` the first time the app launches (and only the first time). Th
Utterances aren't included in these files (`vocab.txt` is standard across all models and just used to decode outputs from the model into words). You're right that the size of the metadata will vary based on the number of intents/slots used in the model, but "greatly" has to be taken in context—that fill will be orders of magnitude smaller than the model, which shouldn't change in size frequently.

It's all hair-splitting, though. The wording's OK—it's just that "drastically" seemed a bit...drastic :).

2020-09-01 14:49 UTC, space-pope approved these changes
Thanks for the new content! :shipit:

2020-09-01 14:55 UTC, merged

2020-09-01 23:02 UTC, timmywil commented
:tada: This PR is included in version 1.25.0 :tada:

The release is available on [GitHub release](https://github.com/spokestack/spokestack.io/releases/tag/1.25.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: